---
title: "Soybean Yield Gap Analysis Clean Code"
author: "Sam Wallace"
date: "2025-01-31"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This markdown includes "clean", as in more direct code of the R code files in the Soybean_yga/Code folder for more centralized and cleaner use in analysis. R markdown is created by Sam Wallace

```{r Libraries,echo=F,results=F}
library(tidyverse)
library(emmeans)
library(lme4)
library(modelr)
library(ggpmisc)
library(lmerTest)
library(glmmTMB)
library(DHARMa)
library(shades)
library(MuMIn)
library(meta)
library(metafor)
library(here)
library(ggpubr)
library(performance)
library(janitor)
library(fitdistrplus)
library(Metrics)

options(contrasts = c("contr.sum", "contr.poly")) #setting contrasts
```

```{r Read in PRISM weather data}
#### PRISM weather data was extracted from python based API provided by Ben Eck from NRCC. The files here are raw data from there and are cleaned in this chunk.

PrismRaw2Clean <- function(csvpath, location){
  
  # Reads in raw file based on the file path including the file name and .csv. The here function is locating the r project location, so anything in the path will come after the project location in your file path.
  raw_prism = read_csv(here(csvpath))
  colnames(raw_prism) = c("date", "maxt", "mint", "prcp")
  raw_prism$date <- as.Date(raw_prism$date, format = "%m/%d/%Y")
  
  # This converts the english units from PRISM into metric and also finds the day of year for each entry.
  # Location input is the experimental site to use later in joins
  f_to_c <- 5/9
  clean_prism <- raw_prism %>%
    mutate(Year = year(date),
           doy = yday(date),
           maxt_c = (maxt-32)*f_to_c,
           mint_c = (mint-32)*f_to_c,
           prcp_cm = prcp*2.54,
           Location = rep(location ,nrow(raw_prism))) %>%
  dplyr::select(Year, date, doy, maxt_c, mint_c, prcp_cm, Location) %>%
    filter(Year > 1980)
  return(clean_prism)
}

# Now you can get your metric prism data for each location by just referencing the file path
musgrave_prism <- PrismRaw2Clean(csvpath = "R_data/Weather_data/PRISM/Raw_prism_files/musgrave_prism.csv", location = "Musgrave")
geneva_prism <- PrismRaw2Clean(csvpath = "R_data/Weather_data/PRISM/Raw_prism_files/geneva_prism.csv", location = "Geneva")
arlington_prism <- PrismRaw2Clean(csvpath = "R_data/Weather_data/PRISM/Raw_prism_files/arlington_prism.csv", location = "AARS")
psu_prism <- PrismRaw2Clean(csvpath = "R_data/Weather_data/PRISM/Raw_prism_files/psu_prism.csv", location = "Rock Springs")

write_csv(musgrave_prism, file = "R_data/Weather_data/PRISM/musgrave_prism_clean.csv")
write_csv(arlington_prism, file = "R_data/Weather_data/PRISM/arlington_prism_clean.csv")

```

```{r Precip normals graphs}
musgrave_2024 <- musgrave_prism %>%
  filter(Year == 2024,
         date >= "2024-05-01", # This was the start date of when I wanted to sum precipitation; if doing annual no need to filter down
         date <= "2024-11-15") %>%
  mutate(cum_rain = cumsum(prcp_cm)) # cumsum() function finds a cummulative sum of a column

musgrave_average <- musgrave_prism %>%
  mutate(day_month = format(date, "%m-%d"),
         doy = yday(date)) %>%
  filter(day_month >= "05-01" & day_month <= "11-15") %>% 
  group_by(doy) %>%
  arrange(date) %>%
  mutate(mean_prcp = mean(prcp_cm)) %>%
  ungroup() %>% 
  filter(Year == 2024) %>% # I put this year here so I could plot it against my other data with the same year
  mutate(avg_cum_rain = cumsum(mean_prcp))


primary_max <- max(musgrave_2024$prcp_cm)
sec_max <- max(musgrave_average$avg_cum_rain)
scale_factor <- sec_max/primary_max


mus_prcp_graph_2024 <- musgrave_2024 %>%
  ggplot(aes(x = date)) +
  theme_bw() +
  geom_bar(aes(y = prcp_cm, fill = "Daily rainfall (cm)"),stat = "identity") +
  scale_y_continuous(name = "Daily Rainfall (cm)",
    limits = c(0,primary_max),
    sec.axis = sec_axis(~.*scale_factor, name = "Cummulative rainfall (cm)")) +
  geom_line(aes(y = cum_rain/scale_factor, colour = "2024 cumulative"), linewidth = 1) +
  geom_line(data = musgrave_average,aes(x = date,y = avg_cum_rain/scale_factor, colour = "Long-term average"),
                                        linewidth = 1)+
  labs(y = "Daily rainfall (cm)", x = "Date", colour = "", fill = "") +
  scale_color_manual(values = c("2024 cumulative" = "black", "Long-term average" = "red")) +
  scale_fill_manual(values = c("Daily rainfall (cm)" = "gray")) +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position = "top",
        legend.text = element_text(size = 12)) +
  scale_x_date(
    date_breaks = "1 month",
    date_labels = "%b",     
    expand = c(0, 0)          
  )
ggsave(mus_prcp_graph_2024, filename = "Figures/mus_prcp_2024.png", dpi = 300,
       width = 8, height = 5, units = "in")

arl_2024 <- arlington_prism %>%
  filter(Year == 2024,
         date >= "2024-05-01", # This was the start date of when I wanted to sum precipitation; if doing annual no need to filter down
         date <= "2024-11-15") %>%
  mutate(cum_rain = cumsum(prcp_cm)) # cumsum() function finds a cummulative sum of a column

arl_average <- arlington_prism %>%
  mutate(day_month = format(date, "%m-%d"),
         doy = yday(date)) %>%
  filter(day_month >= "05-01" & day_month <= "11-15") %>% # If doing annual I do not think you need to filter, but if you do just use start and end of year
  group_by(doy) %>%
  arrange(date) %>%
  mutate(mean_prcp = mean(prcp_cm)) %>%
  ungroup() %>% 
  filter(Year == 2024) %>% # I put this year here so I could plot it against my other data with the same year
  mutate(avg_cum_rain = cumsum(mean_prcp))


primary_max <- max(arl_2024$prcp_cm)
sec_max <- pmax(max(arl_average$avg_cum_rain), sum(arl_2024$prcp_cm))
scale_factor <- sec_max/primary_max


arl_prcp_graph_2024 <- arl_2024 %>%
  ggplot(aes(x = date)) +
  theme_bw() +
  geom_bar(aes(y = prcp_cm, fill = "Daily rainfall (cm)"),stat = "identity") +
  scale_y_continuous(name = "Daily Rainfall (cm)",
    limits = c(0,primary_max),
    sec.axis = sec_axis(~.*scale_factor, name = "Cummulative rainfall (cm)")) +
  geom_line(aes(y = cum_rain/scale_factor, colour = "2024 cumulative"), linewidth = 1) +
  geom_line(data = musgrave_average,aes(x = date,y = avg_cum_rain/scale_factor, colour = "Long-term average"),
                                        linewidth = 1)+
  labs(y = "Daily rainfall (cm)", x = "Date", colour = "", fill = "") +
  scale_color_manual(values = c("2024 cumulative" = "black", "Long-term average" = "red")) +
  scale_fill_manual(values = c("Daily rainfall (cm)" = "gray")) +
  theme(axis.title = element_text(size = 16),
        axis.text = element_text(size = 14),
        legend.position = "top",
        legend.text = element_text(size = 14)) +
  scale_x_date(
    date_breaks = "1 month",
    date_labels = "%b",     
    expand = c(0, 0)          
  )
ggsave(arl_prcp_graph_2024, filename = "Figures/arl_prcp_2024.png", dpi = 300,
       width = 8, height = 5, units = "in")
```

```{r Precipitation Frequency Analysis}
# Code to check 
prism_list <- list(musgrave_prism, arlington_prism, geneva_prism, psu_prism)

process_weather_data <- function(weather_data) {
  
  
  periods <- list(
  "1981 - 2002" <- 1981:2002,
  "2003 - 2024" <- 2003:2024
  )
  
  # Function to calculate annual maxima for each period
  calculate_annual_max <- function(year_range) {
    weather_data %>%
      filter(Year %in% year_range) %>%
      group_by(Year) %>%
      summarize(max_precip = max(prcp_cm*1.13, na.rm = TRUE))
  }
  
  # Get annual maxima for each period
  annual_max_list <- lapply(periods, calculate_annual_max)
  
  # Function to fit lognormal distribution and calculate return levels
  fit_lognormal <- function(annual_max) {
    annual_max <- annual_max$max_precip[annual_max$max_precip > 0]
    
    fit <- fitdist(annual_max, "lnorm")  # Fit lognormal distribution
    return(fit)
  }
  
  # Fit lognormal distribution to each period
  lognormal_fits <- lapply(annual_max_list, fit_lognormal)
  
  # Calculate return levels
  return_periods <- seq(5,100,5)
  
  calculate_return_levels <- function(fit) {
    # Extract parameters
    meanlog <- fit$estimate["meanlog"]
    sdlog <- fit$estimate["sdlog"]
    
    # Calculate return levels
    return_levels <- qlnorm(1 - (1 / return_periods), meanlog = meanlog, sdlog = sdlog)
    
    # Return levels as a data frame
    data.frame(
      Return_Period = return_periods,
      Return_Level = return_levels
    )
  }
  
  # Calculate return levels for each period
  return_levels_list <- lapply(lognormal_fits, calculate_return_levels)
  
  # Combine results into a single data frame for all periods
  return_levels_df <- bind_rows(
    data.frame(Period = "1981 - 2002", return_levels_list[[1]]),
    data.frame(Period = "2003 - 2024", return_levels_list[[2]]
  ))
  
  return(return_levels_df)
}

return_times_sites <- lapply(prism_list, process_weather_data)

combined_results <- bind_rows(
  lapply(seq_along(return_times_sites), function(i) {
    data.frame(Data_Set = paste("Data", i), return_times_sites[[i]])
  })
)

combined_results <- combined_results %>%
  mutate(site = case_match(Data_Set, 
                           "Data 1" ~ "Musgrave",
                           "Data 2" ~ "AARS",
                           "Data 3" ~ "Geneva",
                           "Data 4" ~ "Rock Springs"))

# Plot rainfall distributions of return times for each site and color dots by the time period
precip_freq <- combined_results %>%
  ggplot(aes(x = Return_Period, y = Return_Level, color = Period)) +
  geom_point() +
  geom_line() +
  facet_wrap(~site) + 
  theme_bw() +
  theme(legend.position = "top") +
  scale_color_manual(values = c("#1E88E5", "#FFC107")) +
  labs(y = "1-Day precipitation event (cm)",x = "Return period (Years)", color = "" ) +
  theme(axis.title = element_text(size = 18),
        axis.text = element_text(size = 16),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16))
ggsave(precip_freq, filename = here("Figures/prcp_freq_sites.png"),dpi = 300, width = 9, height = 6, units = "in")
```

```{r Read in soybean agronomic data}
# Read in all soybean data from raw file
soy_rye_raw <- read_csv(here("R_data/Soy_rye_data/NY_WI_NTvT_master.csv"))

# Select only rows that can be useful for further analysis
# Also editing experiment name for 2018 so I can model it differently
soy_rye_useful <- soy_rye_raw %>%
  mutate(ExperimentName = case_when(Field == "RN30" ~ "White Mold",
                                    Field == "RN20" ~ "White Mold",
                                    .default = ExperimentName)) %>%
  dplyr::select(Year, State, Location, ExperimentName, Rep, SoySeedingDate, Till_NT,
         RyeBiomass_kgha, SoyStand_ha, Per_Emergence, WeedBiomass_kgha, Yield_Mgha, Yield_buac, ExperimentalTrt, SoySeedingRate_ha) %>%
  filter(ExperimentName != "CIG NT Soybeans") %>%
  mutate(SoySeedingDate = as.Date(SoySeedingDate, format = "%m/%d/%y")) %>%
  filter(SoySeedingDate != "2019-10-06") %>%
  mutate(ExperimentName = case_when(SoySeedingDate == "2018-06-06"~ "No-Till Soy Split Plot",
                                    .default = ExperimentName),
         Location = case_when(State == "PA" ~ "Rock Springs", .default = Location)) %>%
  filter(State != "PA",
         Location != "Geneva")


# Count number of no-till and tilled plots for each experiment and year of the experiment
nt_t_counts <- soy_rye_useful %>%
  group_by(ExperimentName, Year) %>%
  mutate(nt_count = sum(Till_NT == "NT")) %>%
  mutate(till_count = sum(Till_NT == "Till")) %>%
  distinct(ExperimentName, till_count, nt_count)
```

```{r Function to get planting precipitation before and after}
#### These functions are for getting independent variables for later use in meta analysis, such as precip before and after planting, GDD, etc. These are variables that are climatically based and vary by site year
planting_precip <- function(met_df, mgmt_df, station_site){

  # met_df: Dataframe that includes precipitation data, year, and date at least to calculate precipitation around planting.
  # mgmt_df: Dataframe that includes soybean management and agronomic information, including planting date
  # station_site: String input for the name of experimental site (Musgrave, Arlington, Geneva, PSU, etc.)

# Find planting dates for the location for each experiment and year
  planting_dates <- mgmt_df %>%
    group_by(Year, Location) %>%
    slice_min(SoySeedingDate)%>%
    ungroup() %>%
    filter(Location == station_site) %>%
    dplyr::select(ExperimentName, Year, State, Location, SoySeedingDate) %>%
    distinct()
  
  exp_df <- left_join(met_df, planting_dates, by = c("Year","Location")) %>%
    mutate(plant_doy = yday(SoySeedingDate))
#### Calculates the precipitation +/- 15 days around planting period for each planting date at the site 
  plant_prcp <- exp_df %>%
    filter(!is.na(SoySeedingDate) & doy >= plant_doy - 15 & doy<= plant_doy + 15) %>%
    group_by(ExperimentName, Year, State, Location, SoySeedingDate) %>%
    summarise(plant_prcp = sum(prcp_cm, na.rm = T), .groups = "drop")
  return(plant_prcp)
}

iem_mus <- read_csv("R_data/Weather_data/mus_iem.csv")
iem_mus <- iem_mus %>%
  mutate(Year = year,
         doy = day,
         prcp_cm = rain/10,
         Location = rep("Musgrave"))
  
iem_aars <- read_csv("R_data/Weather_data/aars_iem.csv")
iem_aars <- iem_aars %>%
  mutate(Year = year,
         doy = day,
         prcp_cm = rain/10,
         Location = rep("AARS"))


#More functions to come depending on variables that we investigate, but format will be similar regardless of variable
musgrave_plant_prcp <- planting_precip(met_df = iem_mus, mgmt_df = soy_rye_useful, station_site = "Musgrave")
wi_plant_prcp <- planting_precip(met_df = iem_aars, mgmt_df = soy_rye_useful, station_site = "AARS")


all_plant_prcp <- rbind(musgrave_plant_prcp, wi_plant_prcp)
comb_soy_prcp <- left_join(soy_rye_useful, all_plant_prcp, by = c("Year", "State", "Location", "ExperimentName"))
```

```{r Function to get rye biomass}
#### These functions are for getting independent variables for later use in meta analysis, such as precip before and after planting, GDD, etc. These are variables that are climatically based and vary by site year
rye_biomass <- function(mgmt_df, station_site){
  # mgmt_df: Dataframe that includes soybean management and agronomic information, including planting date

#### Finds rye biomass associated with a block for comparison of yields by tillage in differing levels of rye biomass
  rye_bm <- mgmt_df %>%
    group_by(ExperimentName, Year, State, Location, Rep) %>%
    mutate(rye_bm = ifelse(is.na(RyeBiomass_kgha), 
                           RyeBiomass_kgha[Till_NT == "NT"], 
                           RyeBiomass_kgha)) %>%
    summarise(rye_bm = mean(rye_bm, na.rm = TRUE)) %>%
    ungroup()

  return(rye_bm)
}

all_rye<- rye_biomass(soy_rye_useful)


mus_wi_rye <- all_rye %>%
  filter(Location %in% c("Musgrave", "AARS")) %>%
  drop_na() %>%
  group_by(Location, ExperimentName, Year) %>%
  summarise(rye_mean = mean(rye_bm)) %>%
  ungroup()

rye_by_state <- mus_wi_rye %>%
  group_by(Location) %>%
  summarise(mean_rye = mean(rye_mean))

exps_w_rye <- mus_wi_rye$ExperimentName

soy_ylds <- soy_rye_useful %>%
  dplyr::select(ExperimentName, Year, State, Location, Rep, Till_NT, Yield_Mgha) %>%
  filter(ExperimentName %in% exps_w_rye)

comb_rye_prcp <- left_join(mus_wi_rye, soy_ylds,by = c("Year", "State", "ExperimentName", "Rep"))
```

```{r Function to get each experiments yield data set up for meta analysis}
get_model_inputs <- function(soy_data, experiment_name){
  # This function gets the data for each individual experiment to be used for creating each model
  model_input <- soy_data %>%
    filter(ExperimentName %in% experiment_name) %>%
    drop_na(Year) %>%
    mutate(Year = as.factor(Year)) %>%
    mutate(block = Rep)
}
 
experiment_names <- unique(comb_soy_prcp$ExperimentName)

# For loop below used to easily extract each dataframe for my experiments
input_list <- list()
for(i in 1:length(experiment_names)){
  input_list[[i]] <- get_model_inputs(comb_soy_prcp, experiment_names[i])
  clean_name <- gsub("[^a-zA-Z0-9]", "_", tolower(experiment_names[i]))
  df_name <- paste0(clean_name, "_inputs")
  assign(df_name, input_list[[i]])
}

# Data need to be further filtered by each experiment to only extract the "control" NT treatments and the tilled comparison. Experiments needing this are: Starter fert, seeding depth, coulter study, ccbrt, wisc. 2018, mowtivation, wi-2015.

sf_filter_inputs <- starter_fertilizer_study_inputs %>%
  filter(ExperimentalTrt == "Tilled" | ExperimentalTrt == "Control")
  
sd_filter_inputs <- seeding_depth_study_inputs %>%
  filter(ExperimentalTrt == "Tilled" | ExperimentalTrt == "1.75") # Need to figure out what seeding depth was used in tillage

#coulter_filter <- coulter_study_inputs %>%
 # filter(ExperimentalTrt == "Tilled no coulter" | ExperimentalTrt == "Straight coulter") # Talk to chris or ben about what coulter type to include
  
wi_2020 <- ccbrt_soybean_inputs %>%
  filter(Year == 2020 & (ExperimentalTrt == "Control" | endsWith(ccbrt_soybean_inputs$ExperimentalTrt,"r"))) # filter to only include the planter data, not drilled

wi_2019 <- ccbrt_soybean_inputs %>%
  filter(Year == 2019)

mowtivation_filter <- mowtivation_inputs %>%
  filter(ExperimentalTrt == "TIC" | ExperimentalTrt == "RNO")
  
wi_2015_filter <- no_till_soybeans_inputs %>%
  filter(startsWith(ExperimentalTrt, "Tilled") | startsWith(ExperimentalTrt, "0 "))

wi_2017_filter <- no_till_soybeans_inputs %>%
  filter(Year == 2017)

wi_2018 <- comb_soy_prcp %>%
  filter(ExperimentName == "No-Till Soy Split Plot") %>%
  separate_wider_delim(ExperimentalTrt, delim = " ", names = c("main_plot","split_plot")) %>%
  group_by(Rep,main_plot) %>%
  mutate(Yield_Mgha_2 = mean(Yield_Mgha))

wi_2018_mod <- lmer(log(Yield_Mgha) ~ main_plot*split_plot + (1|Rep:main_plot) + (1:Rep),
                    data = wi_2018)

wi_2018_filter <- comb_soy_prcp %>%
  filter(ExperimentName == "No-Till Soy Split Plot") %>%
  mutate(block = Rep)
summary(wi_2018_mod)
check_model(wi_2018_mod)
emmeans(wi_2018_mod, pairwise ~ split_plot|main_plot, type = "response")

ocs_inputs <- ocs_inputs %>%
  filter(Year == 2018)

combined_filtered_results <- rbind(barns_inputs, moss_inputs, sf_filter_inputs, sd_filter_inputs,
                                   coulter_study_inputs, wi_2020, wi_2019, mowtivation_filter,
                                   wi_2015_filter, wi_2017_filter, ocs_inputs, wi_2018_filter)
combined_filtered_results <- combined_filtered_results %>%
  mutate(Year = as.numeric(as.character(Year)),
         site_year = paste0(Location,"-",Year)) 
```

```{r T test of yields}
t_test_soy_yield <- combined_filtered_results %>%
  group_by(Year, Location) %>%
  summarize(t_test = list(t.test(Yield_Mgha ~ Till_NT))) %>%
  mutate(
    t_statistic = sapply(t_test, function(x) x$statistic),
    p_value = sapply(t_test, function(x) x$p.value),
    mean_tillage_1 = sapply(t_test, function(x) x$estimate[1]),
    mean_tillage_2 = sapply(t_test, function(x) x$estimate[2])
  )


soy_prcp_w_pvals <- left_join(combined_filtered_results, t_test_soy_yield)

soy_prcp_w_pvals <- soy_prcp_w_pvals %>%
  mutate(label = case_when(
      p_value < 0.05 & Till_NT == "Till"~ "*",
      p_value > 0.05 & Till_NT == "Till"~ "" ,
      !is.na(p_value) & Till_NT == "Till" ~ "*" 
    )
  ) %>%
  group_by(Year, Location, ExperimentName, Till_NT) %>%
  mutate(mean_yield = mean(Yield_Mgha)) %>%
  mutate(se_yield = sd(Yield_Mgha)/sqrt(n())) %>%
  ungroup() %>%
  distinct(Year, Location, ExperimentName, mean_yield, se_yield, p_value, label, Till_NT, site_year)

soy_prcp_w_pvals$Year[soy_prcp_w_pvals$Year == 2021 & soy_prcp_w_pvals$ExperimentName == "Seeding Depth Study"] <- "2021a" 
soy_prcp_w_pvals$Year[soy_prcp_w_pvals$Year == 2021 & soy_prcp_w_pvals$ExperimentName == "Starter Fertilizer Study"] <- "2021b" 



location_labels <- c("AARS" = "Arlington, WI", "Musgrave" = "Aurora, NY")

soy_pval_graph <- soy_prcp_w_pvals %>%
  ggplot(aes(x = Year, y = mean_yield, fill = Till_NT)) +
  geom_col(width = 0.6,  position = position_dodge(width = 0.6)) +
  geom_errorbar(aes(ymin = mean_yield-se_yield, ymax = mean_yield+se_yield), width = 0.2, position = position_dodge(width = 0.6)) +
  geom_text(aes(label = label, colour = "black", y = mean_yield+se_yield), size = 12, show.legend = FALSE, color = "black") +
  facet_wrap(~Location, nrow = 3, scales = "free_x", labeller = as_labeller(location_labels)) +
  scale_fill_manual(values = c("#3B528BFF", "#FDE779"), 
                    labels = c("NT" = "No-till", "Till" = "Till")) +
  theme_bw() +
  labs(y = expression(paste("Mean yield, " , "(kg ", " ", ha^{-1}, ")")),
       fill = "", 
       x = 'Year') +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 14),
        axis.text.x = element_text(angle = 45, vjust = 0.7),
        strip.text = element_text(size = 14),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14),
        legend.position = "top") 
ggsave(soy_pval_graph, filename = here("Figures/yield_by_tillage_pvals_metric.png"), dpi = 300, 
       width = 8, height = 5, units = "in")
```

```{r Seeing if Lmer on all data works}

combined_mixmod <- lmer(log(Yield_Mgha) ~ Till_NT*site_year + (1|Location:Year:block),
                        data = combined_filtered_results)
summary(combined_mixmod)
check_model(combined_mixmod)

comb_emm <- emmeans(combined_mixmod, pairwise~Till_NT|site_year, type = "response")

comb_contrasts <- as.data.frame(comb_emm$contrasts)

contrast_plus_data <- combined_filtered_results %>%
  left_join(comb_contrasts) %>%
  dplyr::select(Year, State, Location, ExperimentName, SoySeedingDate.y, ratio, SE, plant_prcp, site_year, Per_Emergence) %>%
  rename("SoySeedingDate" = SoySeedingDate.y,
         "yield_gap" = ratio) %>%
  distinct()

contrast_plus_data$SoySeedingDate[contrast_plus_data$ExperimentName == "Starter Fertilizer Study"] <- as.Date("2021-06-04", format = "%Y-%m-%d")
contrast_plus_data$plant_prcp[contrast_plus_data$ExperimentName == "Starter Fertilizer Study"] = 7.44



# Plot the output of the meta analysis
contrast_plus_data %>%
  ggplot(aes(x = plant_prcp, y = yield_gap))+
  geom_point(aes(color = State), size = 2) +
  geom_errorbar(aes(ymin = ci(yield_gap, SE)$lower, ymax = ci(yield_gap,SE)$upper, colour = State), width = 0.2) + # Error bars for CI
  #geom_text(aes(label  = site_year)) +
  labs(x = "Precipitation accumulation +/- 15 days of planting (cm)",
       y = "Ratio of no-till yield to tilled yield",
       color = "") +
  stat_poly_eq(formula = y~x, use_label(c("R2", "eq")), size = 5)+
  theme_pubr() +
  scale_color_manual(values = c("black", "red")) +
  geom_smooth(method = "lm",formula = y ~ x,  se = FALSE, color = "gray", 
              linetype = "dashed")  +
  theme(axis.title = element_text(size = 18),
        axis.text = element_text(size = 16),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16))
## Method seems to introduce a lot of standard error, but this could be due to how I am modeling

```

```{r Looking at stand count}
# Soybean density of NT treatments
filter_w_stand <- combined_filtered_results %>%
  #filter(Till_NT == "NT") %>%
  group_by(Year, ExperimentName, Till_NT) %>%
  drop_na(SoyStand_ha) 

filter_w_stand %>%
  ggplot(aes(x = site_year, y = Per_Emergence, colour = Till_NT)) +
  geom_point() +
  facet_wrap(~Location, scales = "free_x", nrow = 2) +
  theme_pubr()


stand_per_year <-site_yearstand_per_year <- filter_w_stand %>%
  group_by(site_year, Till_NT) %>%
  summarise(stand_m2 = mean(SoyStand_ha/10000),
            seed_m2 = mean(as.numeric(SoySeedingRate_ha)/10000))

def_stands <- c(-41.64,8.68,1.62,0.073,-6.76,7.77,47.05,23.43,8.91, 21.78, -92.93, -133, -17.61, 
                -29.6, -50.14, -27.6, 20.3, -46.78, 4.43, -85.44, -15.22, -42.31, 1.9)
stand_w_def <- data.frame(stand_per_year, def_stands)
stand_w_def <- stand_w_def %>%
  mutate(per_stand = stand_m2/seed_m2,
         site = case_when(
                          startsWith(site_year,"A") ~ "AARS",
                          startsWith(site_year, "M") ~ "Musgrave"))

stand_w_def %>%
  filter(site_year  != c("Musgrave-2024","Musgrave-2023")) %>%
  ggplot(aes(x = def_stands, y = per_stand, color = site, shape = Till_NT)) +
  geom_point() +
  geom_smooth(method = "lm", se = F) +
  stat_poly_eq(use_label(c("eq","R2"))) +
  theme_pubr()



stand_w_prcp <- filter_w_stand %>%
  left_join(all_plant_prcp)

stand_model <- lmer(Yield_Mgha ~  Per_Emergence*plant_prcp + (1|ExperimentName:Year:Rep) + (1|ExperimentName:Year), 
                    data =stand_w_prcp)

summary(stand_model)
performance::r2(stand_model)

boxplot(filter_w_stand$Yield_Mgha)


filter_w_stand %>%
  #filter(as.numeric(SoySeedingRate_ha) <= 617500) %>%
  ggplot(aes(x = Per_Emergence, y = Yield_Mgha)) +
  geom_point() +
  facet_wrap(~SoySeedingRate_ha) +
  theme_pubr() +
  stat_poly_eq(method = "lm", formula = y ~ x + 0) +
  geom_smooth(method = "lm", formula = y ~ x + 0) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))

nrow(filter_w_stand %>%
  filter(as.numeric(SoySeedingRate_ha) <= 617500))
    
nt_all_vars <- stand_w_prcp %>%
  drop_na(RyeBiomass_kgha, WeedBiomass_kgha)

stand_prcp_mod <- lmer(Yield_Mgha ~  plant_prcp + (1|ExperimentName:Year:Rep) + (1|ExperimentName:Year), data = stand_w_prcp)
summary(stand_prcp_mod)
performance::r2(stand_prcp_mod)
stand_prcp_emm <- emtrends(stand_prcp_mod, var = "plant_prcp")
summary(stand_prcp_emm, infer = c(T,T))


stand_prcp_mod_nt <- lmer(Per_Emergence ~  plant_prcp + (1|ExperimentName:Year:Rep) + (1|ExperimentName:Year), data = stand_w_prcp)
summary(stand_prcp_mod_nt)
stand_prcp_emm_nt <- emtrends(stand_prcp_mod_nt, var = "plant_prcp")
summary(stand_prcp_emm_nt, infer = c(T))
performance::r2(stand_prcp_mod_nt)

soy_emg_plot <- filter_w_stand %>%
  ggplot(aes(x = Per_Emergence, y = Yield_Mgha)) +
  geom_point(size = 2, aes(colour = State)) +
  scale_color_manual(values = c("black", "red")) +
  theme_pubr()  +
  stat_poly_eq() +
  geom_smooth(method = "lm") +
  labs(y = "Soybean yield (Mg/ha)", x = "Percent emergence (%)", color = "") +
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 14))

ggsave(soy_emg_plot, filename = "Figures/soy_emg_plot.png", dpi = 300,
       width = 8, height = 5, units = "in")

 #### Looking into rye biomass with NT
soy_nt_rye <- combined_filtered_results %>%
  filter(Till_NT == "NT") %>%
  group_by(Year, ExperimentName, Rep) 

rye_yld_mod <- lmer(Yield_Mgha ~  RyeBiomass_kgha + (1|ExperimentName/Year/Rep), data = soy_nt_rye)

summary(rye_yld_mod)
performance::r2(rye_yld_mod) ### Super bad R^2 for just the rye biomass

library(scales)


soy_rye_yld <- soy_nt_rye %>%
  ggplot(aes(x =RyeBiomass_kgha, y = Yield_Mgha, color = State)) +
 # facet_wrap(~State, scales = "free") +
  geom_point(size = 2) +
  scale_color_manual(values = c("black", "red")) +
  theme_pubr()  +
  labs(y = "Soybean yield (Mg/ha)", x = "Cereal rye biomass at termination (kg/ha)", color = "") +
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 14))

ggsave(soy_rye_yld, filename = "Figures/soy_rye_yield_all.png", dpi = 300,
       width = 8, height = 5, units = "in")


ny_rye <- soy_nt_rye %>%
  filter(State == "NY") %>%
  ungroup() %>%
  dplyr::select(RyeBiomass_kgha)

wi_rye <- soy_nt_rye %>%
  filter(State == "WI") %>%
  ungroup() %>% 
  dplyr::select(RyeBiomass_kgha)


t.test(ny_rye$RyeBiomass_kgha, wi_rye$RyeBiomass_kgha, paired = F) # T test shows that the rye biomass is significantly different in WI than NY.

#### Looking at weed biomass

soy_nt_weeds <- soy_nt_rye %>%
  drop_na(WeedBiomass_kgha) %>%
  mutate(WeedBiomass_kgha = as.numeric(WeedBiomass_kgha))

soy_weed_mod <- lmer(Yield_Mgha ~  log(WeedBiomass_kgha+0.1) +  (1|ExperimentName/Year/Rep), data = soy_nt_weeds)

summary(soy_weed_mod)
check_model(soy_weed_mod)
performance::r2(soy_weed_mod)

nt_weed_plot <- soy_nt_weeds %>%
  ggplot(aes(x = WeedBiomass_kgha, y = Yield_Mgha)) +
  geom_point(aes(color = State)) +
  theme_pubr() +
  scale_color_manual(values = c("black", "red")) +
  labs(y = "Soybean yield (Mg/ha)", x = "Weed biomass (kg/ha)", color = "") +
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 14))

ggsave(nt_weed_plot, filename = "Figures/Soy_nt_weeds.png", dpi = 300,
       width = 8, height = 5, units = "in")


emg_crbm <- filter_w_stand %>%
  mutate(exp_year = paste(ExperimentName, Year)) %>%
  drop_na(RyeBiomass_kgha) %>%
  ggplot(aes(x = RyeBiomass_kgha, y = Per_Emergence)) +
  geom_point(size = 2, aes(colour = State)) +
  theme_pubr() +
  scale_color_manual(values = c("black", "red")) +
  geom_smooth(method = "lm") +
  stat_poly_eq(size = 5) +
  labs(y = "Soybean emergence (%)", x = "Cereal rye biomass at termination (kg/ha)", color = "") +
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 14))

ggsave(emg_crbm, filename = "Figures/Soy_emg_rye_bm.png", dpi = 300,
       width = 8, height = 5, units = "in")

emg_rye_mod <- lmer(Per_Emergence ~ RyeBiomass_kgha +  (1|ExperimentName:Year:Rep) + (1|ExperimentName:Year) + (1|ExperimentName), data = filter_w_stand)
check_model(emg_rye_mod)
performance::r2(emg_rye_mod)
summary(emg_rye_mod)



tot_model <- lmer(Yield_Mgha ~ RyeBiomass_kgha+plant_prcp+as.numeric(WeedBiomass_kgha)+Per_Emergence  + (1|ExperimentName:Year:Rep) , data = filter_w_stand)
check_model(tot_model)
performance::r2(tot_model)
summary(tot_model)

```

```{r Model the data}
get_soy_model <- function(soy_data, experiment_name, check_assumptions = TRUE){
  
  model_input <- soy_data %>%
    filter(ExperimentName %in% experiment_name) %>%
    drop_na(Year)
  
   exp_mod <- if(length(unique(soy_data$Year[soy_data$ExperimentName %in% experiment_name])) > 1){
        lmer(log(Yield_Mgha) ~ as.factor(Till_NT)*as.factor(Year) + (1|Year:block), data = model_input)
  } else{
    lmer(log(Yield_Mgha) ~ as.factor(Till_NT)*Year + (1|block), data = model_input)
  }
   
   if(check_assumptions){
    par(mfrow = c(2, 2))  # Arrange diagnostic plots
    
    # 1. Residuals vs Fitted - Check homoscedasticity
    plot(residuals(exp_mod) ~ fitted(exp_mod), 
         main = "Residuals vs Fitted",
         xlab = "Fitted Values", 
         ylab = "Residuals")
    abline(h = 0, col = "red")
    
    # 2. Normal Q-Q Plot - Check normality of residuals
    qqnorm(residuals(exp_mod), main = "Normal Q-Q")
    qqline(residuals(exp_mod), col = "red")
    
    # Check normality of random effects
    ranef_df <- ranef(exp_mod)
    qqnorm(unlist(ranef_df), main = "Random Effects Q-Q")
    qqline(unlist(ranef_df), col = "red")
  }
   
   mod_emm <- emmeans(exp_mod,pairwise ~Till_NT|as.factor(Year))
 
  contrast_df <- as.data.frame(mod_emm$contrasts) %>%
    dplyr::select(Year, estimate, SE) %>%
    mutate(ExperimentName = experiment_name) %>%
    rename(yield_gap = estimate)
  
  return(contrast_df)
}  
# Look at tweedie GLMM --> naturally allows variance to be non-consistent
library(nlme)
# Homogeneous variance model
model_hom <- lme(Yield_Mgha ~ Till_NT, random = ~ 1 | block, data = ocs_inputs)

# Heterogeneous variance model
model_het <- lme(Yield_Mgha ~ Till_NT,
                 random = ~ 1 | block,
                 weights = varIdent(form = ~ 1 | Till_NT),
                 data = ocs_inputs)

# Likelihood ratio test
anova(model_hom, model_het)
plot(resid(model_het)~predict(model_het))

emmeans(model_het, ~Till_NT)


barns_emm <- get_soy_model(combined_filtered_results, experiment_name = "BARNS", check_assumptions = T)
moss_emm <- get_soy_model(combined_filtered_results, experiment_name = "MOSS")
ocs_emm <- get_soy_model(combined_filtered_results, experiment_name = "OCS")
coulter_emm <- get_soy_model(combined_filtered_results, experiment_name = "Coulter Study")
sf_emm <- get_soy_model(combined_filtered_results, experiment_name = "Starter Fertilizer Study")
sd_emm <- get_soy_model(combined_filtered_results, experiment_name = "Seeding Depth Study")
mowtivation_emm <- get_soy_model(combined_filtered_results, experiment_name = "Mowtivation")
wi_nt_soy_emm <- get_soy_model(combined_filtered_results, experiment_name = "No-Till Soybeans")
wi_ccbrt_emm <- get_soy_model(combined_filtered_results, experiment_name = "CCBRT Soybean")
wi_2018_emm <- get_soy_model(combined_filtered_results, experiment_name = "No-Till Soy Split Plot")
#rose2_emm <- get_soy_model(comb_soy_prcp, experiment_name = "ROSE2")
#rose3_emm <- get_soy_model(comb_soy_prcp, experiment_name = "ROSE3")


# Combine all of the contrasts into one dataframe
total_contrasts <- rbind(barns_emm, moss_emm, ocs_emm,
                         mowtivation_emm, coulter_emm, sf_emm, sd_emm,
                         wi_nt_soy_emm, wi_ccbrt_emm, wi_2018_emm)#,
                        # rose2_emm, rose3_emm)
```

```{r Meta analysis work}
# Create inpput for meta analysis
meta_input <- combined_filtered_results %>%
  #mutate(Year = (Year)) %>%
  left_join(total_contrasts) %>%
  dplyr::select(Year, State, Location, ExperimentName, SoySeedingDate.y, yield_gap, SE, plant_prcp) %>%
  rename("SoySeedingDate" = SoySeedingDate.y) %>%
  mutate(site_year = paste0(State, "-", Year)) %>%
  distinct() %>%
  filter(site_year != "NY-2021")

#meta_input <- left_join(meta_input, all_spring_gdd, by = c("Year", "State", "Location"))

#meta_input <- meta_input %>%
 # dplyr::select(-SoySeedingDate) %>%
#  rename("SoySeedingDate" = SoySeedingDate.y,
 #        "ExperimentName" = ExperimentName.x)

meta_input$SoySeedingDate[meta_input$ExperimentName == "Starter Fertilizer Study"] = as.Date("2021-06-04", format = "%Y-%m-%d")
meta_input$plant_prcp[meta_input$ExperimentName == "Starter Fertilizer Study"] = 7.44


meta_input %>%
  filter(State != "PA") %>%
  ggplot(aes(x = plant_prcp, y = exp(yield_gap))) +
  geom_point(aes(color = State))+
  #stat_poly_eq(formula = y~x, use_label(c("R2", "eq")), size = 5)+
  theme_pubr() +
  scale_color_manual(values = c("black", "slateblue", "red")) +
 # geom_smooth(method = "lm",formula = y ~ x,  se = FALSE, color = "gray", 
              #linetype = "dashed")  +
  theme(axis.title = element_text(size = 18),
        axis.text = element_text(size = 16),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16))
  

# Run the meta analysis
metagen_analysis <- metagen(data = meta_input, TE = yield_gap, seTE = SE, studlab = site_year)

# Save the results into this dataframe
metagen_result <- data.frame(
  effect_size = metagen_analysis$TE,  # Treatment effect
  ci_lower = metagen_analysis$lower,  # Lower bound of confidence interval
  ci_upper = metagen_analysis$upper,  # Upper bound of confidence interval
  i2 = metagen_analysis$I2            # I² for heterogeneity
)

# Combine with identifying data and rainfall data
metagen_result_comb <- cbind(metagen_result, meta_input)

# Transform the outputs to a linear scale from the log scale
metagen_result_final <- metagen_result_comb %>%
  mutate(yield_ratio = exp(yield_gap),
         lowerci_trans = exp(ci_lower),
         upperci_trans = exp(ci_upper)) #%>%
  #filter(site_year != "PA-2016" & site_year != "PA-2023" & site_year != "PA-2022")

# Plot the output of the meta analysis
ratio_yg_meta <- metagen_result_final %>%
  ggplot(aes(x = plant_prcp, y = yield_ratio))+
  geom_point(aes(color = State), size = 2) +
  geom_errorbar(aes(ymin = lowerci_trans, ymax = upperci_trans, colour = State), width = 0.2) + # Error bars for CI
  geom_text(aes(label  = site_year)) +
  labs(x = "Precipitation accumulation +/- 15 days of planting (cm)",
       y = "Ratio of no-till yield to tilled yield",
       color = "") +
  stat_poly_eq(formula = y~x, use_label(c("R2", "eq")), size = 5)+
  theme_pubr() +
  scale_color_manual(values = c("black", "red")) +
  geom_smooth(method = "lm",formula = y ~ x,  se = FALSE, color = "gray", 
              linetype = "dashed")  +
  theme(axis.title = element_text(size = 18),
        axis.text = element_text(size = 16),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16))
ggsave(ratio_yg_meta, filename = "Figures/ratio_yg_metaplot.png",dpi = 300,
       width = 9, height = 6, units = "in")


# Actual meta analysis work; above is simply just plotting effects from each lmer model against precipiation and getting an R squared value

metafor_metareg <- rma.mv(yi = effect_size, V = SE^2,
                          data = metagen_result_final, slab = ExperimentName,
                          random = ~ 1 |ExperimentName/site_year,
                          test = "t", method = "ML",
                          mods = ~ plant_prcp)
metafor_metareg

summary(metafor_metareg)
metafor_metareg


emm_meta <- emmprep(metafor_metareg)

prcp_values <- seq(min(metagen_result_final$plant_prcp), 
                   max(metagen_result_final$plant_prcp), 
                   length.out = 30)

em_out <- emmeans(emm_meta, ~plant_prcp, at = list(plant_prcp = prcp_values))
summary(em_out)

prcp_qdrg <- qdrg(object = metafor_metareg, data = metagen_result_final, at = list(prcp_values))
emmeans(prcp_qdrg, ~plant_prcp)
pred_meta <- predict(metafor_metareg, newmods = prcp_values)

pred_df <- data.frame(plant_prcp = prcp_values, 
                      predicted = exp(pred_meta$pred), 
                      SE = pred_meta$se, 
                      CI_low = exp(pred_meta$ci.lb), 
                      CI_high = exp(pred_meta$ci.ub))

pred_df %>%
  ggplot(aes(x = plant_prcp, y = predicted)) +
  geom_point() +
  geom_errorbar(aes(ymin = CI_low, ymax = CI_high)) +
  theme_bw()


fitted_vals <- predict(metafor_metareg)$pred

# Marginal R²: how much variance in observed values (yi) is explained by fixed effects
R2_marginal <- 1 - (var(residuals(metafor_metareg, type="response")) / var(metafor_metareg$yi))


new_data <- data.frame(plant_prcp = seq(min(metagen_result_final$plant_prcp), 
                                        max(metagen_result_final$plant_prcp), 
                                        length.out = 15))

pred <- predict(metafor_metareg, newmods = new_data$plant_prcp)

null_model <- rma.mv(yi = effect_size, V = SE^2, 
                     random = ~ 1 | ExperimentName/site_year,
                     data = metagen_result_final, method = "REML")

1-(metafor_metareg$QE/null_model$QE)

sigma2_metareg <- sum(metafor_metareg$sigma2)  
sigma2_null <- sum(null_model$sigma2)           

pseudo_r2 <- 1 - (sigma2_metareg / sigma2_null)
pseudo_r2 <- round(pseudo_r2, 3)

p_value <- metafor_metareg$pval[2]

new_data$pred <- exp(pred$pred)
new_data$ci.lb <- exp(pred$ci.lb)
new_data$ci.ub <- exp(pred$ci.ub)

# Plot the predictions with confidence intervals
metaplot <- ggplot(new_data_nlme, aes(x = plant_prcp, y = pred)) +
  geom_point(data = metagen_result_final, 
             aes(x = plant_prcp, y = yield_ratio, colour = State), 
             alpha = 0.95, size = 2) +
  geom_errorbar(data = metagen_result_final,
                aes(x = plant_prcp, y = yield_ratio,
                    ymin = lowerci_trans, ymax = upperci_trans, colour = State), width = 0.2) +
  geom_label(data = metagen_result_final, aes(x = plant_prcp, y = yield_ratio, label = site_year)) +
  annotate("text", x = 4, y=1.2, label = paste("R² =", round(pseudo_r2,3)), size = 5) +
  labs(x = "Precipitation +/- 15 days of planting (cm)", 
       y = "Ratio of no-till to tilled yield",
       color = "") +
  theme_pubr() +
  geom_line(data = new_data_nlme, aes(x = plant_prcp, y = predicted), color = "blue", size = 1, linetype = "dashed") +
  #geom_smooth(method = "lm", formula = y ~ x
   #           ,data = metagen_result_final, aes(x = plant_prcp, y = yield_ratio)) +
  scale_color_manual(values = c("black", "red")) +
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14),
        plot.caption = element_text(size = 14),
        plot.caption.position = "plot",
        legend.position = "top") 

ggsave(metaplot, filename = "Figures/metaplot_w_points_nlme.png", dpi = 300,
       width = 9, height = 6, units = "in")

### Looking at non-linear function
library(nlme)
set.seed(123)

# Fit nonlinear model
fit <- nls(yield_ratio ~ L + (U - L) / (1 + exp(-k * (plant_prcp - x0))),
           data = metagen_result_final,
           start = list(L = 0.5, U = 1.1, k = 0.7, x0 = 8))
summary(fit)

group_data <- groupedData(yield_ratio~plant_prcp|as.factor(ExperimentName), data = metagen_result_final)

nlme_fit <- nlme(yield_ratio ~ L + (U - L) / (1 + exp(-k * (plant_prcp - x0))),
           data = group_data,
           start = c(L = 0.5, U = 1.1, k = 0.7, x0 = 8),
           fixed = L + U + k + x0 ~ 1,
           random = x0 ~ 1 |State,
           method = "ML")

plot(augPred(nlme_fit))
nlme::augPred(nlme_fit, data = getData(nlme_fit))

metagen_result_final$pred_group <- predict(nlme_fit, level = 1)

metagen_result_final %>%
  dplyr::select(ExperimentName, pred_fixed, pred_group, plant_prcp) %>%
  pivot_longer(cols = c(pred_fixed, pred_group), names_to = "pred", values_to = "value") %>%
  ggplot(aes(y = value, x = plant_prcp, color = pred)) +
  geom_point() +
  geom_line() +
  theme_pubr()



nlme_ran <- ranef(nlme_fit)$U
qqnorm(nlme_ran)
qqline(nlme_ran)



summary(nlme_fit)
check_model(nlme_fit)
new_data_nlme <- data.frame(
  plant_prcp = seq(min(metagen_result_final$plant_prcp),
                   max(metagen_result_final$plant_prcp),
                   length.out = 100),
  site_year = NA  # so random effect is not added
)
library(nlraa)

cor(predict(nlme_fit, level = 1), metagen_result_final$yield_ratio)^2

metagen_result_final$pred_fixed <- predict(nlme_fit, level = 0)

resid_fixed <- metagen_result_final$yield_ratio - metagen_result_final$pred_fixed

ss_res_fixed <- sum(resid_fixed^2)
ss_total <- sum((metagen_result_final$yield_ratio - mean(metagen_result_final$yield_ratio))^2)
r2_marginal <- 1 - ss_res_fixed / ss_total

# Predict using only fixed effects
new_data_nlme$predicted <- predict(nlme_fit, newdata = new_data_nlme, level = 0)

em_nlme <- emmeans(nlme_fit, ~ plant_prcp, at = list(plant_prcp = 10), 
                        param = names(fixef(nlme_fit)),)

summary(em_nlme, infer = c(TRUE, TRUE), level = 0.95)
# Calculate RMSE and pseudo-R²
residuals <- residuals(nlme_fit)
rmse <- sqrt(mean(residuals^2))
ss_total <- sum((metagen_result_final$yield_ratio - mean(metagen_result_final$yield_ratio))^2)
ss_residual <- sum(residuals^2)
pseudo_r2 <- 1 - (ss_residual / ss_total)
###

nlme_ci <- intervals(nlme_fit, which = "fixed")$fixed
pred_se <- sqrt(t(c(1, 10)) %*% vcov(nlme_fit) %*% c(1, 10))

yield_ratio <- seq(0.6,1,0.1)
precip_by_ratio <- rep(NA, length(yield_ratio))

for(i in 1:length(yield_ratio)){
  precip_by_ratio[i] <- (log(yield_ratio[i])+0.5508)/0.033
}
precip_by_ratio_df <- data.frame(yield_ratio, precip_by_ratio)



### Looking at NLME and confidence intervals
x_vals <- seq(min(metagen_result_final$plant_prcp),
              max(metagen_result_final$plant_prcp),
              length.out = 100)

newdata <- data.frame(plant_prcp = x_vals)

# Bootstrap predictions
set.seed(123)
boot_preds <- replicate(300, {
  boot_data <- metagen_result_final[sample(nrow(metagen_result_final), replace = TRUE), ]
  fit_try <- try(update(nlme_fit, data = boot_data), silent = TRUE)
  if (inherits(fit_try, "try-error")) return(rep(NA, length(x_vals)))
  predict(fit_try, newdata = newdata, level = 0)
})

# Clean up failed bootstraps
boot_preds <- boot_preds[, colSums(is.na(boot_preds)) == 0]

# Calculate 95% CI bands
ci_lower <- apply(boot_preds, 1, quantile, probs = 0.025)
ci_upper <- apply(boot_preds, 1, quantile, probs = 0.975)
ci_mean  <- apply(boot_preds, 1, mean)

plot(yield_ratio ~ plant_prcp, data = metagen_result_final, pch = 16, col = 'gray')
lines(x_vals, ci_mean, col = "blue", lwd = 2)
lines(x_vals, ci_lower, col = "blue", lty = 2)
lines(x_vals, ci_upper, col = "blue", lty = 2)


target_y <- 0.89

x_lo <- approx(x = ci_lower, y = x_vals, xout = target_y)$y
x_hi <- approx(x = ci_upper, y = x_vals, xout = target_y)$y

cat("Approximate x-range where CI includes y =", target_y, ":\n")
cat("From x ≈", round(x_lo, 2), "to x ≈", round(x_hi, 2), "\n")
```

```{r APSIM Yield Data}
apsim_raw <- readxl::read_xlsx("~/Downloads/Soybean_Yga_project.xlsx")

apsim_update <- apsim_raw %>%
  mutate(year = year(Clock.Today)) %>%
  group_by(SimulationName, year) %>%
  summarise(final_soy = max(soy_kg_ha, na.rm = T)) %>%
  ungroup() %>%
  mutate(tillage = case_when(
    SimulationName == "Daymet Tillage" ~ "Till",
    .default = "No Till"
  )) %>%
  filter(final_soy > 0)

apsim_nt <- apsim_update %>%
  filter(tillage == "No Till",
         year %in% proj_yields$Year) 


proj_yields <- combined_filtered_results %>%
  group_by(State, Year, Till_NT) %>%
  summarise(mean_yld = 1000*mean(Yield_Mgha))

proj_nt <- proj_yields %>%
  filter(Till_NT == "NT")

apsim_update %>%
  filter(year > 2013) %>%
  ggplot(aes(x = year, y = final_soy, colour = tillage)) +
  geom_point() +
  geom_line() +
  theme_bw() + 
  geom_point(data = proj_yields, aes(x = Year, y = mean_yld, color = Till_NT)) + 
  geom_line(data = proj_yields, aes(x = Year, y = mean_yld, color = Till_NT)) + 
  labs(x = "Year", y = "Soybean yield (Kg/ha)", color = "Tillage")



apsim_rye <- read_csv("~/Downloads/Soybean_Yga_project.Report.csv")

apsim_rye_upd <- apsim_rye %>%
  mutate(Year = year(as.Date(Clock.Today, format = "%m/%d/%y")))  %>%
  group_by(Year) %>%
  summarise(final_rye = max(rye_bm_kg_ha, na.rm = T)) %>%
  ungroup() 

apsim_rye_upd %>%
  ggplot(aes(x = Year, y = final_rye)) +
  geom_line(linewidth = 2) +
  geom_point(size = 3) +
  theme_bw() +
  labs(x = "Year", y = "Cereal rye biomass (kg/ha)")




rye_obs <- comb_soy_prcp %>%
  filter(State == "NY" | State == "WI") %>%
  group_by(Year, State) %>%
  summarise(final_rye = mean(RyeBiomass_kgha, na.rm = T)) %>%
  mutate(type = rep("obs")) %>%
  filter(Year != 2017 & Year != 2020 & Year != 2024)


apsim_preds <- apsim_rye_upd %>%
  mutate(type = rep("preds")) %>%
  filter(Year %in% rye_obs$Year)

pred_obs <- rbind(apsim_preds, rye_obs)


pred_obs %>%
  ggplot(aes(x = factor(Year), y = final_rye, color = type)) +
  geom_line(aes(group = type)) + 
  geom_point() +
  theme_pubclean() +
  labs(x = "Year", y = "Cereal rye biomass (Kg/ha)", color = "")

pred_obs_wide <- pred_obs %>%
  pivot_wider(values_from = final_rye,names_from = type) 

rye_pred_obs_plot <- pred_obs_wide %>%
  ggplot(aes(x = obs, y = preds)) +
  geom_abline(slope = 1) +
  geom_point() +
  theme_pubr() +
  geom_text(aes(x = 3550, y = 9400, label =paste0("R-RMSE: ",r_rmse," %")), size = 5) +
  labs(x = "Observed cereal rye biomass (kg/ha)", y = "Predicted cereal rye biomass (kg/ha)") +
  stat_poly_eq(size = 5) +
  coord_cartesian(ylim = c(3000, 10000), xlim = c(3000,10000)) +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 14),
        strip.text = element_text(size = 14),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14))
ggsave(rye_pred_obs_plot, filename = "Figures/cr_pred_obs.png",
       dpi = 300, width = 9, height = 6, units = "in")


mean(soy_rye_raw$RyeSeedingRate_lbac[soy_rye_raw$State == "NY"], na.rm = T)

rmse_rye <- rmse(pred_obs_wide$preds,pred_obs_wide$obs)
mean_rye_obs <- mean(pred_obs_wide$obs)
r_rmse <- round((rmse_rye/mean_rye_obs)*100,2)


nse_top <- sum((pred_obs_wide$preds-pred_obs_wide$obs)^2)
nse_bot <- sum((pred_obs_wide$obs-mean(pred_obs_wide$obs))^2)
nse <- 1-(nse_top/nse_bot)

weed_obs <- comb_soy_prcp %>%
  filter(Location == "Musgrave",
         Till_NT == "NT") %>%
  group_by(Year) %>%
  summarise(weed_bm = mean(as.numeric(WeedBiomass_kgha), na.rm = T),
            mean_rye = mean(RyeBiomass_kgha, na.rm = T)) %>%
  mutate(type = rep("obs"))

weed_obs %>%
  ggplot(aes(x = weed_bm, y = mean_rye)) +
  geom_smooth(se = F, method = "lm") +
  geom_point() +
  stat_poly_eq() +
  theme_pubclean()


mus_rye_apsim_match <- read_csv("~/Downloads/rye_model_experiments.Report.csv")

mus_apsim_rye_upd <- mus_rye_apsim_match %>%
  mutate(Year = year(as.Date(Clock.Today, format = "%m/%d/%y")))  %>%
  group_by(Year) %>%
  summarise(final_rye_pred = max(rye_bm_kg_ha, na.rm = T)) %>%
  ungroup() %>%
  filter(Year %in% rye_obs$Year) 

real_obs_pred <- left_join(mus_apsim_rye_upd, rye_obs)


rye_pred_obs_real <- real_obs_pred %>%
  ggplot(aes(x = final_rye, y = final_rye_pred)) +
  geom_abline(slope = 1) +
  geom_point() +
  theme_pubr() +
  #geom_text(aes(x = 3550, y = 9400, label =paste0("R-RMSE: ",r_rmse," %")), size = 5) +
  labs(x = "Observed cereal rye biomass (kg/ha)", y = "Predicted cereal rye biomass (kg/ha)") +
  stat_poly_eq(size = 5) +
  coord_cartesian(ylim = c(3000, 11000), xlim = c(3000,11000)) +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 14),
        strip.text = element_text(size = 14),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14))


rmse_rye <- rmse(real_obs_pred$final_rye_pred,real_obs_pred$final_rye)
mean_rye_obs <- mean(real_obs_pred$final_rye)
r_rmse <- round((rmse_rye/mean_rye_obs)*100,2)


nse_top <- sum((real_obs_pred$final_rye_pred-real_obs_pred$final_rye)^2)
nse_bot <- sum((real_obs_pred$final_rye-mean(real_obs_pred$final_rye))^2)
nse <- 1-(nse_top/nse_bot)

```

```{r Comaring NEWA to PRISM}

mus_newa_23 <- clean_names(read_csv("~/Downloads/mus_2023_newa.csv"))

mus_newa_metric <- mus_newa_23 %>%
  mutate(date_newa = as.Date(date, format = "%m/%d/%y"),
         prcp_newa = total_precipitation*2.54,
         mint_c_newa = (min_air_temp_f-32)*(5/9),
         maxt_c_newa = (max_air_temp_f-32)*(5/9)) %>%
  dplyr::select(date_newa, prcp_newa, mint_c_newa, maxt_c_newa) %>%
  mutate(dataset_newa = rep("NEWA"))

prism_2023 <- musgrave_prism %>%
  filter(Year == 2023) %>% 
  mutate(dataset = rep("PRISM")) %>%
  dplyr::select(date, prcp_cm, mint_c, maxt_c, dataset)


compare_met <- cbind(mus_newa_metric, prism_2023)

compare_met <- compare_met %>%
  mutate(cum_newa_prcp = cumsum(prcp_newa),
         cum_prism_prcp = cumsum(prcp_cm))


compare_met %>%
  ggplot(aes(x = prcp_newa, y = prcp_cm)) +
  geom_point() +
  geom_abline(slope = 1) +
  stat_poly_eq(formula = y~x, use_label(c("R2", "eq")), size = 5) +
  theme_pubr()

cor(compare_met$prcp_newa, compare_met$prcp_cm)^2


nse_top <- sum((compare_met$cum_prism_prcp-compare_met$cum_newa_prcp)^2)
nse_bot <- sum((compare_met$cum_newa_prcp-mean(compare_met$cum_newa_prcp))^2)
nse <- 1-(nse_top/nse_bot)
```

```{r Soybean ANCOVA}
ancova_data <- combined_filtered_results %>%
  mutate(Till_NT = as.factor(Till_NT),
         pdoy = yday(SoySeedingDate.x)) %>%
  filter(Year < 2024)

ancova_data$plant_prcp[ancova_data$ExperimentName == "Starter Fertilizer Study"] <- 7.44

ancova_mod2 <-  lmer(Yield_Mgha ~ Till_NT*plant_prcp + (1|State:ExperimentName:Year:block) + (1|State:ExperimentName:Year) +
                     (1|ExperimentName),
                   data = ancova_data)

car::Anova(ancova_mod2, type =3)


summary(ancova_mod2)
check_model(ancova_mod2)
performance::r2(ancova_mod2)
hist(resid(ancova_mod2))
qqnorm(resid(ancova_mod2))
qqline(resid(ancova_mod2))

plot(ancova_mod2)

ancova_slopes <- emtrends(ancova_mod2,pairwise ~ Till_NT, var = "plant_prcp")
summary(ancova_slopes, infer = c(T, T))


emmeans(ancova_mod2, ~ Till_NT, at = list(plant_prcp = 0))



emmip(ancova_mod2, Till_NT ~ plant_prcp, cov.reduce = range)


library(ggeffects)

gg_preds <- ggpredict(ancova_mod2, terms = c("plant_prcp","Till_NT"))

summary(ancova_mod2)
fixed_effects <- fixef(ancova_mod)

#till_eq <- paste0("y = ", round(fixed_effects[1],3), " + ", round(fixed_effects[3],3), "x")
#nt_eq <- paste0("y = ",round(fixed_effects[1]+fixed_effects[2],3), " + ", round(fixed_effects[3]+fixed_effects[4],3),"x")

ancova_plot <- ancova_data %>% 
  group_by(ExperimentName,Year, Till_NT) %>%
  mutate(mean_yield = mean(Yield_Mgha)) %>%
  ggplot() +
  geom_point(aes(x = plant_prcp, y = mean_yield, colour = Till_NT, shape = State), size =3) +
  geom_line(data = gg_preds, aes(x = x, y = predicted, colour = group)) +
  geom_ribbon(data = gg_preds, aes(x = x,ymin = conf.low, ymax = conf.high,fill  = group),alpha = 0.2) +
  scale_color_manual(values = c("black", "red"))+
  scale_shape_manual(values = c("triangle","square")) +
  scale_fill_manual(values = c("black","red")) +
  #annotate("text", x = 12, y = 5, label = nt_eq, color = "black", size = 5) +
  #annotate("text", x = 12, y = 4.8, label = till_eq, color = "red", size = 5) +
  theme_pubr() + 
  labs(y = "Soybean yield (Mg/ha)", x = "Precipitation recieved +/- 15 days of planting (cm)", fill = "", shape = "", color = "") +
  guides(fill = "none") +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.text = element_text(size = 12))


stand_model


doy_mod <-  lmer(Yield_Mgha ~ (Till_NT) * pdoy + (1|State:ExperimentName:Year:block) + (1|State:ExperimentName:Year) +
                     (1|ExperimentName),
                   data = ancova_data %>% filter(Year < 2024))

summary(doy_mod)
check_model(doy_mod)
performance::r2(doy_mod)
hist(resid(doy_mod))
qqnorm(resid(doy_mod))
qqline(resid(doy_mod))

doy_trends <- emtrends(doy_mod,pairwise ~ Till_NT, var = "pdoy")
summary(doy_trends, infer = c(T,T))

emmeans(doy_mod, ~ Till_NT, at = list(pdoy = 0))

gg_preds_doy <- ggpredict(doy_mod, terms = c("pdoy","Till_NT"))

ancova_data %>% 
  group_by(ExperimentName,Year, Till_NT) %>%
  mutate(mean_yield = mean(Yield_Mgha)) %>% 
  filter(Year < 2024) %>%
  ggplot() +
  geom_point(aes(x = pdoy, y = mean_yield, colour = Till_NT, shape = State), size =3) +
  geom_line(data = gg_preds_doy, aes(x = x, y = predicted, colour = group)) +
  geom_ribbon(data = gg_preds_doy, aes(x = x,ymin = conf.low, ymax = conf.high,fill  = group),alpha = 0.2) +
  scale_color_manual(values = c("black", "red"))+
  scale_shape_manual(values = c("triangle","square")) +
  scale_fill_manual(values = c("black","red")) +
  theme_pubr() + 
  labs(y = "Soybean yield (Mg/ha)", x = "Planting day of year", fill = "", shape = "", color = "") +
  guides(fill = "none") +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.text = element_text(size = 12))


#### Looking at return times of precipitation for all planting periods

get_window_sums_multiple_doys <- function(weather_data, doy_targets, window_size = 15) {
  
  
  all_years <- unique(weather_data$Year)
  
  result_list <- map(doy_targets, function(doy_target) {
    sums <- map_dbl(all_years, function(yr) {
      this_year <- weather_data %>% filter(Year == yr)
      window_days <- ((doy_target - window_size):(doy_target + window_size)) %% 366
      window_days[window_days == 0] <- 366  # Wrap-around fix
      this_year %>%
        filter(doy %in% window_days) %>%
        summarise(sum_precip = sum(prcp_cm, na.rm = TRUE)) %>%
        pull(sum_precip)
    })
    tibble(DOY = doy_target, Year = all_years, SumPrecip = sums)
  })
  
  bind_rows(result_list)
}

musgrave_doys <- unique(yday(combined_filtered_results$SoySeedingDate.x[combined_filtered_results$Location == "Musgrave"]))

precip_sums_mus <- get_window_sums_multiple_doys(musgrave_prism, seq(150,170,1))

target_value_ny <- 10 #### From the meta analysis, this is the precipitation to get 90% of the till yield in NT

return_periods_df <- precip_sums_mus %>%
  group_by(DOY) %>%
  arrange(desc(SumPrecip)) %>%
  mutate(
    Rank = row_number(),
    n = n(),
    ReturnPeriod = (n + 1) / Rank
  ) %>%
  summarise(
    TargetReturnPeriod = approx(x = log(SumPrecip), y = ReturnPeriod, xout = log(target_value_ny))$y,
    .groups = "drop"
  )

return_periods_df %>%
  ggplot(aes(x = DOY, y = TargetReturnPeriod)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x) +
  theme_pubr() +
  stat_poly_eq(formula = y~x) +
  labs(y = "Return period for target precipitation (years)", x = "Day of year", title = "Musgrave")

compute_return_period_df <- function(df) {
  sums <- df$SumPrecip
  sorted <- sort(sums, decreasing = TRUE)
  ranks <- rank(-sorted, ties.method = "first")
  n <- length(sorted)
  tibble(
    Precip = sorted,
    ReturnPeriod = (n + 1) / ranks
  )
}

return_curves_df <- precip_sums_mus %>%
  group_by(DOY) %>%
  summarise(ReturnData = list(compute_return_period_df(cur_data())),
            .groups = "drop") %>%
  unnest(ReturnData)

return_curves_df %>%
  ggplot(aes(x = ReturnPeriod, y = Precip)) +
  geom_point() +
  geom_line() +
  facet_wrap(~DOY,scales = "free") +
  theme_pubr() +
  geom_hline(yintercept = 13.53, color = "red")

### Same stuff for Wisconsin

wi_doys <- unique(yday(combined_filtered_results$SoySeedingDate.x[combined_filtered_results$Location == "AARS"]))

precip_sums_arl <- get_window_sums_multiple_doys(arlington_prism, seq(150,170,2))

return_curves_wi <- precip_sums_arl %>% 
  filter(SumPrecip > 0) %>%
  group_by(DOY) %>%
  summarise(
    Fit = list(fitdist(SumPrecip, "lnorm")),
    Sums = list(SumPrecip),
    .groups = "drop"
  ) %>%
  mutate(
    ReturnData = map(Sums, function(x) {
      sorted <- sort(x, decreasing = TRUE)
      ranks <- rank(-sorted, ties.method = "first")
      n <- length(sorted)
      return_periods <- (n + 1) / ranks
      tibble(Precip = sorted, ReturnPeriod = return_periods)
    })
  )

target_value_wi <- 10
return_periods_df_wi <- precip_sums_arl %>%
  group_by(DOY) %>%
  arrange(desc(SumPrecip)) %>%
  mutate(
    Rank = row_number(),
    n = n(),
    ReturnPeriod = (n + 1) / Rank
  ) %>%
  summarise(
    TargetReturnPeriod = approx(x = log(SumPrecip), y = ReturnPeriod, xout = log(target_value_wi))$y,
    .groups = "drop"
  )

return_periods_df_wi %>%
  ggplot(aes(x = DOY, y = TargetReturnPeriod)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x) +
  theme_pubr() +
  stat_poly_eq(formula = y~x) +
  labs(y = "Return period for target precipitation (years)", x = "Day of year", title = "Arlington") #### Wisconsin plot is really linear!!!


return_curves_df_wi <- precip_sums_arl %>%
  group_by(DOY) %>%
  summarise(ReturnData = list(compute_return_period_df(cur_data())),
            .groups = "drop") %>%
  unnest(ReturnData)

return_curves_df_wi %>%
  ggplot(aes(x = ReturnPeriod, y = Precip)) +
  geom_point() +
  geom_line() +
  facet_wrap(~DOY,scales = "free") +
  theme_pubr() +
  geom_hline(yintercept = 13.53, color = "red") #### This plot hints that Wisconsin frequently gets more sufficient rain for this system to work at getting 90% of Till yield in NT
```

```{r Saxton and Rawls Pedotransfer Function}
#### Function to estimate field capacity (theta 33 kpa) and wilting point (theta 1500 kpa) from soil textural data. 
#### Equations from Saxton and Rawls 2006 paper Soil Water Characteristic Estimates by Texture and Organic Matter for Hydrologic Solutions

sax_rawl_fc_wp <- function(sand, silt, clay, org_mat = 0.03){
  theta_1500t <- (-0.024*sand)+(0.487*clay)+(0.006*org_mat)+(0.005*(sand*org_mat))-(0.013*clay*org_mat)+(0.068*clay*sand)+0.031
  theta_1500 <- theta_1500t + ((0.14*theta_1500t)-0.02)
  
  theta_33t <- (-0.251*sand)+(0.195*clay)+(0.011*org_mat)+(0.006*sand*org_mat)-(0.027*clay*org_mat)+(0.452*sand*clay)+0.299
  theta_33 <- theta_33t + (1.283*(theta_33t)^2-0.374*theta_33t-0.015)
  
  soil_wat_df <- data.frame(theta_1500, theta_33)
  return(soil_wat_df)
}

ocs_fc_wp <- sax_rawl_fc_wp(sand = 0.3959, silt = 0.4114, clay = 0.1927, org_mat = 0.03)

B <- (log(1500)-log(33))/(log(ocs_fc_wp$theta_33)/log(ocs_fc_wp$theta_1500))
A <- exp(log(33)+(B*log(ocs_fc_wp$theta_33)))

psi_theta <-function(theta){
  psi <- A*((theta)^-B)
  psi_theta_df <- data.frame(theta,psi)
  return(psi_theta_df)
}

thetas <- psi_theta(theta = seq(0.13,0.3,0.01))

thetas %>%
  ggplot(aes(x = theta*100, y = psi)) +
  geom_line() +
  geom_point() + 
  theme_pubr() +
  labs(x = "Water potential (kPa)", y = "Volumetric water content (%)") +
  scale_y_log10()
  
  
#### SWCON for APSIM #### 

bd_mus <- c(1.290,1.330, 1.470, 1.470, 1.640, 1.700, 1.700)

dul_mus <- c(0.250, 0.227, 0.200, 0.200, 0.163, 0.150, 0.150)

po_mus <- 1-(bd_mus/2.65)

swcon_mus <- (po_mus-dul_mus)/po_mus


#### Van G ####
library(soilDB)

df_ocs <- data.frame(
  sand = 39.59, silt = 41.14, clay = 19.27,
  bulk_density = 1.3
)

df_aars <- data.frame(
  sand = 16, silt = 64, clay = 20,
  bulk_density = 0.153
)

van_pars <- ROSETTA(df_ocs, vars = names(df_ocs), v = "3", include.sd = T)

van_aars <- ROSETTA(df_aars, vars = names(df_aars), v = "3", include.sd = T)

theta_r <- van_aars$theta_r
theta_s <- van_aars$theta_s
alpha <- 10^van_aars$alpha
n <- 10^van_aars$npar
m <- 1 - (1/n)

# Psi range
psi_cm <- seq(1, 1500, 1)*10.197

# Retention curve
theta <- theta_r + (theta_s - theta_r) / ((1 + (alpha * psi_cm)^n)^m)

theta_1500 <- data.frame(
  psi = 1500,
  theta_1500 = theta_r + (theta_s - theta_r) / ((1 + (alpha * 1500)^n)^m)
)

chat_df <- data.frame(psi_cm, theta)

chat_df %>%
  ggplot(aes(x = log10((psi_cm)/10.197), y = theta)) +
  geom_line() +
  #geom_point(data = theta_1500, aes(x = (psi) ,y = theta_1500)) +
  theme_pubr() +
  labs(x = "Water potential (log10(kPa))", y = "Volumetric water content") 
  

psi33_cm <- 33 * 10.197
psi1500_cm <- 1500 * 10.197

theta33 <- theta_r + (theta_s - theta_r) / ((1 + (alpha * psi33_cm)^n)^m)
theta1500 <- theta_r + (theta_s - theta_r) / ((1 + (alpha * psi1500_cm)^n)^m)


#### Monte Carlo Analysis Chat GPT

set.seed(123)

# Parameter means and sds from ROSETTA
param_means <- c(theta_r = van_aars$theta_r, theta_s = van_aars$theta_s, alpha = 10^van_aars$alpha, n = 10^van_aars$npar)
param_sds   <- c(theta_r = van_aars$sd_theta_r, theta_s = van_aars$sd_theta_s, alpha = 10^van_aars$sd_alpha, n = 10^van_aars$sd_npar)

set.seed(1)
n_sim <- 5000
h <- exp(seq(log(1), log(16000), length.out = 150))  # cm suction (positive magnitude)

# helper: truncated normal draw
rtn <- function(n, mean, sd, low=-Inf, high=Inf) {
  x <- rnorm(n, mean, sd)
  x[x < low] <- low
  x[x > high] <- high
  x
}

# 1) sample on native scales
th_r  <- rtn(n_sim, van_aars$theta_r,van_aars$sd_theta_r,low=0)
th_s0 <- rtn(n_sim, van_aars$theta_s,van_aars$sd_theta_s,low=0)
logA  <- rnorm(n_sim, van_aars$alpha, van_aars$sd_alpha)
logN  <- rnorm(n_sim, van_aars$npar,  van_aars$sd_npar)

# optional porosity cap if you know bulk density bd (g/cm3)
# phi <- 1 - bd/2.65
# th_s0 <- pmin(th_s0, phi)

# enforce theta_s >= theta_r

# back-transform strictly-positive params
alpha <- 10^(logA)
npar  <- pmax(10^(logN), 1 + 1e-6)
m     <- 1 - 1/npar

# 2) van Genuchten retention
vg_theta <- function(h, thr, ths, a, n, m) {
  thr + (ths - thr) / ((1 + (a * h)^n)^(m))
}

# 3) evaluate and get pointwise 95% bands
library(matrixStats)
H <- matrix(h, nrow=length(h), ncol=n_sim)
Theta <- vg_theta(H, matrix(th_r,  nrow=length(h), ncol=n_sim, byrow=TRUE),
                     matrix(th_s0,  nrow=length(h), ncol=n_sim, byrow=TRUE),
                     matrix(alpha, nrow=length(h), ncol=n_sim, byrow=TRUE),
                     matrix(npar,  nrow=length(h), ncol=n_sim, byrow=TRUE),
                     matrix(m,     nrow=length(h), ncol=n_sim, byrow=TRUE))

mean_curve <- rowMeans(Theta)
lower <- rowQuantiles(Theta, probs=0.025)
upper <- rowQuantiles(Theta, probs=0.975)



# 4) quick ggplot
library(ggplot2)
df <- data.frame(h=h/10.197, mean=mean_curve, lower=lower, upper=upper)
ggplot(df, aes(x=h)) +
  geom_ribbon(aes(ymin=lower, ymax=upper), alpha=0.25) +
  geom_line(aes(y=mean)) +
  scale_x_log10() +
  coord_cartesian(xlim = c(1, 2000)) +
  labs(x="Pressure head (kPa)", y="θ (cm³/cm³)") +
  theme_pubr()

```

```{r OCS Soil Moisture Data}
ocs_vwc <- read_csv("~/Downloads/ocs_soilmoist_june25.csv")

ocs_vwc$channel_name[ocs_vwc$sensor_sn == "21978491-1"] <- "Soil water content (m³/m³) Zone 1"
ocs_vwc$channel_name[ocs_vwc$sensor_sn == "21978491-2"] <- "Soil water content (m³/m³) Zone 2"
  
ocs_vwc_upd <- ocs_vwc %>%
  separate_wider_delim(alias, delim = "-", names = c("plot", "mgmt")) %>%
  mutate(plot = trimws(plot)) %>%
  mutate(crop = case_when(
    endsWith(plot,"A") ~ "Corn",
    endsWith(plot,"B") ~ "Soybean"
  )) %>%
  mutate(date = as.POSIXct(time, format = "%m/%d/%y %H:%M"),
         month = month(date),
         day = day(date)) %>%
  group_by(month, day, sensor_sn) %>%
  mutate(avg_daily_vwc = mean(value))

ocs_vwc_upd %>%
  ggplot(aes(x = day, y = avg_daily_vwc, colour = plot, linetype = mgmt)) +
  geom_line() +
  facet_wrap(crop~channel_name) +
  theme_pubr() +
  labs(linetype = "", colour = "", y = "Average Daily VWC (mm/mm)",
       x = "Day of June 2025")


```

```{r APSIM Yield Gaps and Water Deficit}
library(readxl)
apsim_yg_def <- read_xlsx("SoyGap_APSIM.xlsx")

apsim_yg_yields <- apsim_yg_def %>%
  group_by(Zone) %>%
  summarise(yield_kg_ha = max(soy_kg_ha),
            rye_bm_kg_ha = max(rye_bm_kg_ha)) %>%
  filter(Zone != "Fallow Field", Zone != "Rye Field") %>%
  separate_wider_delim(cols = Zone, delim = " ", names = c("State", "Tillage", "year_plant"))


rye_ylds <- apsim_yg_yields %>%
  filter(rye_bm_kg_ha > 0,
         Tillage == "NT")

apsim_gaps <- apsim_yg_yields %>%
  separate_wider_delim(cols = Zone, delim = " ", names = c("State", "Tillage", "Year")) %>%
  group_by(State, Year) %>%
  summarise(yield_gap = yield_kg_ha[Tillage == "NT"]/yield_kg_ha[Tillage == "Till"])

apsim_rye_vals <- apsim_yg_yields %>%
  separate_wider_delim(cols = Zone, delim = " ", names = c("State", "Tillage", "Year")) %>%
  filter(Tillage == "NT") %>%
  group_by(State, Year) %>%
  summarise(rye_bm_kg_ha = rye_bm_kg_ha)

plant_dates <- meta_input %>%
  filter(State != "PA") %>%
  dplyr::select(State,SoySeedingDate, site_year) %>%
  distinct()

planting <- soy_rye_useful %>%
  dplyr::select(SoySeedingDate) %>%
  distinct()

apsim_dates <- apsim_yg_def %>%
  mutate(date = as.Date(Clock.Today)) %>%
  dplyr::select(date)

apsim_defs_nt <- apsim_yg_def %>%
  mutate(date = as.Date(Clock.Today)) %>%
  #filter(rye_bm_kg_ha %in% rye_ylds$rye_bm_kg_ha) %>%
  dplyr::select(Zone,SoilWaterDeficit) %>%
  separate_wider_delim(cols = Zone, delim = " ", names = c("State", "Tillage", "year_plant"))


apsim_defs_nt <- apsim_defs_nt[-12,] #### Taking out the second WI 2021b

apsim_defs_till <- apsim_yg_def %>%
  filter(as.Date(Clock.Today) %in% plant_dates$SoySeedingDate,
         grepl("Till", Zone)) %>%
  dplyr::select(Zone,SoilWaterDeficit, Clock.Today) %>%
  separate_wider_delim(cols = Zone, delim = " ", names = c("State", "Tillage", "year_plant")) %>%
  mutate(site_year = paste0(State, "-", year_plant)) %>%
  mutate(year_sim = as.character(year(Clock.Today))) %>%
  group_by(site_year) %>%
  filter(year_sim == year_plant) %>%
  slice_min(Clock.Today) %>%
  ungroup() %>%
  dplyr::select(State, Tillage, year_plant, SoilWaterDeficit)

apsim_till_2021 <- apsim_yg_def %>%
  filter(as.Date(Clock.Today) %in% plant_dates$SoySeedingDate,
         grepl("Till", Zone)) %>%
  dplyr::select(Zone,SoilWaterDeficit, Clock.Today) %>%
  separate_wider_delim(cols = Zone, delim = " ", names = c("State", "Tillage", "year_plant")) %>%
  mutate(site_year = paste0(State, "-", year_plant)) %>%
  mutate(year_sim = as.character(year(Clock.Today))) %>%
  filter(year_sim %in% "2021") %>%
  filter((year_plant == "2021a" & Clock.Today == as.Date("2021-06-02")) | 
         (year_plant == "2021b" & Clock.Today == as.Date("2021-06-04")))  %>%
  dplyr::select(State, Tillage, year_plant, SoilWaterDeficit)

apsim_defs_all <- rbind(apsim_defs_till, apsim_till_2021, apsim_defs_nt)

fin_ap_df <- right_join(apsim_yg_yields, apsim_defs_all)


fin_ap_df %>%
  ggplot(aes(x = SoilWaterDeficit, y = yield_kg_ha, color = Tillage)) +
  geom_point(aes(shape = State)) +
  theme_pubr()

gap_ap <- fin_ap_df %>%
  group_by(State, year_plant) %>%
  summarise(yield_gap = yield_kg_ha[Tillage == "NT"]/yield_kg_ha[Tillage == "Till"],
         sw_diff = abs(SoilWaterDeficit[Tillage == "NT"])-abs(SoilWaterDeficit[Tillage == "Till"]))

gap_ap %>%
  ggplot(aes(x = sw_diff, y = yield_gap, colour = State)) +
  geom_point() +
  theme_pubr() +
  labs(y = "Ratio of no-till to till yield", x = "No-till minus till soil water deficit", color = "")

cor(gap_ap$sw_diff, gap_ap$yield_gap)^2

obs_yg <- metagen_result_final %>%
  dplyr::select(State, Year, yield_ratio) %>%
  mutate(year_plant = as.character(Year))



obs_pred <- left_join(obs_yg, gap_ap) %>%
  drop_na()

cor(obs_pred$yield_ratio, obs_pred$sw_diff)^2



rmse_gap <- Metrics::rmse(obs_pred$yield_gap, obs_pred$yield_ratio)
mean_gap_obs <- mean(obs_pred$yield_ratio)
r_rmse <- round((rmse_gap/mean_gap_obs)*100,2)

ny_obs_pred <- obs_pred %>%
  filter(State == "NY")

NSE <- function(obs, pred) {
  1 - sum((obs - pred)^2) / sum((obs - mean(obs))^2)
}

NSE(obs = ny_obs_pred$yield_ratio, pred = ny_obs_pred$yield_gap)


cor(ny_obs_pred$yield_gap, ny_obs_pred$sw_diff)^2

rye_preds <- apsim_yg_yields %>%
  filter(Tillage == "NT",
         year_plant != "2021a")

rye_preds$year_plant[rye_preds$year_plant == "2021b"] <- "2021"
rye_preds$Year <- as.numeric(rye_preds$year_plant)

NSE(obs = rye_obs$final_rye, pred = rye_preds$rye_bm_kg_ha)

cor(rye_obs$final_rye, rye_preds$rye_bm_kg_ha)^2

#### APSIM Yield gaps with plant population set to plant density (stand count instead of seeding rate)

apsim_yg_def_adj <- read_xlsx("soygap_analysis_no_mc.xlsx")

apsim_defs_adj <- apsim_yg_def_adj %>%
  mutate(date = as.Date(Clock.Today)) %>%
  dplyr::select(Zone, date,frac_water) %>%
  separate_wider_delim(cols = Zone, delim = " ", names = c("State", "Tillage", "year_plant", "soil_scenario", "plant_scenario")) %>%
  mutate(site_year = paste0(State,"-",year_plant))

pd_filtered <- plant_dates %>%
  filter(site_year %in% c("WI-2015", "WI-2017", "WI-2018", "WI-2019", "WI-2023",
                          "NY-2015","NY-2016","NY-2023", "NY-2024"))

df_filtered <- apsim_defs_adj %>%
  semi_join(pd_filtered, by = c("date" = "SoySeedingDate","site_year")) %>%
  dplyr::select(State, Tillage, year_plant, soil_scenario, plant_scenario, frac_water)


apsim_yg_yields_adj <- apsim_yg_def_adj %>%
  group_by(Zone) %>%
  summarise(yield_kg_ha = max(soy_kg_ha),
            rye_bm_kg_ha = max(rye_bm_kg_ha)) %>%
  #filter(Zone != "Fallow Field", Zone != "Rye Field") %>%
  separate_wider_delim(cols = Zone, delim = " ", names = c("State", "Tillage", "year_plant", "soil_scenario", "plant_scenario")) %>%
  mutate(soil_scenario = factor(soil_scenario, levels = c("Low", "Med", "High"))) %>%
  left_join(df_filtered)

rye_ylds <- apsim_yg_yields_adj %>%
  filter(rye_bm_kg_ha > 0,
         Tillage == "NT") %>%
  dplyr::select(-yield_kg_ha) %>%
  mutate(site_year = paste0(State, year_plant),
         type = rep("sim"))  %>%
  dplyr::select(site_year, State, rye_bm_kg_ha)
  
rye_obs_adj <- rye_obs %>%
  ungroup() %>%
  mutate(site_year = paste0(State, Year), 
         rye_bm_kg_ha = final_rye) %>%
  filter(site_year %in% rye_ylds$site_year) %>%
  dplyr::select(site_year, State, rye_bm_kg_ha)


apsim_gaps_adj <- apsim_yg_yields_adj %>%
  group_by(State, year_plant, soil_scenario, plant_scenario) %>%
  mutate(yield_gap = yield_kg_ha[Tillage == "NT"]/yield_kg_ha[Tillage == "Till"],
         water_frac_dif = frac_water[Tillage == "NT"]-frac_water[Tillage == "Till"])

obs_yg_adj <- obs_yg %>%
  filter(year_plant %in% apsim_gaps_adj$year_plant)

adj_gaps_joined <- left_join(apsim_gaps_adj, obs_yg_adj) %>%
  mutate(Year = as.numeric(year_plant))

proj_yields_adj <- proj_yields %>%
  filter(Year %in% adj_gaps_joined$Year)

adj_gaps_yields <- left_join(adj_gaps_joined, proj_yields, by = c("State", "Tillage" = "Till_NT", "Year")) %>%
  group_by(soil_scenario, plant_scenario) %>%
  mutate(rmse_gap = Metrics::rmse(yield_ratio, yield_gap),
         rrmse_gap = rmse_gap/mean(yield_ratio),
         rmse_yield = rmse(mean_yld, yield_kg_ha),
         rrmse_yield = rmse_yield/mean(mean_yld),
         ef_gap = mod_ef(pred = yield_gap, obs = yield_ratio),
         ef_yield = mod_ef(pred = yield_kg_ha, obs = mean_yld),
         soil_scenario = factor(soil_scenario, levels = c("High", "Med", "Low")))

# Graph comparing yields
rrmse_yield <- Metrics::rmse(actual = adj_gaps_yields$mean_yld, 
                             predicted =adj_gaps_yields$yield_kg_ha)/mean(adj_gaps_yields$mean_yld)
rmse_yield <- Metrics::rmse(actual = adj_gaps_yields$mean_yld, 
                             predicted =adj_gaps_yields$yield_kg_ha)
r2_yield <- cor(adj_gaps_yields$mean_yld, adj_gaps_yields$yield_kg_ha)^2

adj_yields_plot <- adj_gaps_yields %>%
  ggplot(aes(x = mean_yld, y = yield_kg_ha)) +
  geom_point(size = 2, aes(colour = State)) +
  geom_abline(slope = 1, intercept = 0) +
  theme_pubr() +
  facet_grid(rows = vars(soil_scenario),cols = vars(plant_scenario)) +
  scale_color_manual(values = c("red", "black")) +
  coord_cartesian(ylim = c(800, 5000), xlim = c(800,5000)) +
  labs(x = "Observed soybean yield (kg/ha)", y = "Simulated soybean yield (kg/ha)", color = "", shape = "") +
  geom_smooth(method = "lm", se = F, color = "gray", linetype = "dashed") +
  stat_poly_eq(size = 4) +
  geom_text(aes(label = paste0("RMSE = ", round(rmse_yield,2)), x = 1200, y = 4300), size = 4,inherit.aes = F) +
  geom_text(aes(label = paste0("RRMSE = ", round(rrmse_yield*100,2),"%"), x = 1200, y = 3800), size = 4,inherit.aes = F) +
  geom_text(aes(label = paste0("EF = ", round(ef_yield,2)), x = 1200, y = 3300), size = 4, inherit.aes = F) +
  theme(legend.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 14))

ggsave(adj_yields_plot, filename = "Figures/yg_adj_yields_plot_no_mc.png",
       dpi = 300, width = 12, height = 8, units = "in")
# Graph comparing gaps
rrmse_gap <- Metrics::rmse(actual = adj_gaps_yields$obs_gap, predicted = adj_gaps_yields$yield_gap)/mean(adj_gaps_yields$obs_gap)
rmse_gap <- Metrics::rmse(actual = adj_gaps_yields$obs_gap, predicted = adj_gaps_yields$yield_gap)
r2_gap <- cor(adj_gaps_yields$obs_gap, adj_gaps_yields$yield_gap)^2

yg_sim_obs_plot <- adj_gaps_yields %>%
  ggplot(aes(x = yield_ratio, y = yield_gap)) +
  geom_point(size = 3, aes(colour = State)) +
  geom_abline(slope = 1, intercept = 0) +
  theme_pubr() +
  facet_grid(rows = vars(soil_scenario) , cols = vars(plant_scenario)) +
  scale_color_manual(values = c("red", "black")) +
  coord_cartesian(ylim = c(0.5, 1.2), xlim = c(0.5,1.2)) +
  labs(x = "Observed soybean yield gap", y = "Simulated soybean yield gap", color = "", shape = "") +
  theme(legend.text = element_text(size = 16),
        axis.title = element_text(size = 16),
        axis.text = element_text(size = 16)) +
  geom_text(aes(label = paste0("RMSE = ", round(rmse_gap,2)), x = 0.56, y = 1.1), size = 4,inherit.aes = F) +
  geom_text(aes(label = paste0("RRMSE = ", round(rrmse_gap*100,2),"%"), x = 0.56, y = 1.04), size = 4,inherit.aes = F) +
  geom_text(aes(label = paste0("EF = ", round(ef_gap,2)), x = 0.56, y = 0.98), size = 4, inherit.aes = F) +
  stat_poly_eq(label.x = 0.155, label.y = 0.85, size = 5) 

ggsave(yg_sim_obs_plot, filename = "Figures/yg_sim_obs_plot.png",
       dpi = 300, width = 9, height = 6, units = "in")

### Yield per year 

adj_wide <- adj_gaps_yields_mc %>%
  dplyr::select(State, year_plant, Tillage, plant_scenario,soil_scenario, yield_kg_ha) %>%
  group_by(State, year_plant, Tillage, plant_scenario) %>%
  pivot_wider(names_from = soil_scenario, values_from = yield_kg_ha) %>%
  ungroup() %>%
  group_by(State, year_plant, plant_scenario) %>%
  mutate(yld_diff_tillage = 100*(Med[Tillage == "NT"]-Med[Tillage == "Till"])/Med[Tillage == "Till"])

labels_ppop <- c("PD" = "Crop density", "SR" = "Seeding rate")

adj_wide %>%
  ggplot(aes(x = year_plant, y = yld_diff_tillage, fill = plant_scenario)) +
  geom_bar(stat = "identity", position = position_dodge(), width = 0.4, color = "black") +
  geom_hline(yintercept = 0) +
  scale_fill_manual(values = c("pink","lightblue"), labels = labels_ppop) +
  facet_wrap(~State, scales = "free_x", nrow = 2) +
  theme_pubr() +
  labs(y = "Difference between no-till and till yield (%)", x = "Year", color = "", fill = "") +
  theme(legend.text = element_text(size = 16),
        axis.title = element_text(size = 16),
        axis.text = element_text(size = 16)) 

61.8*seq(0.25, 1, length.out = 5)

sw_df_plano <- data.frame(dul = c(0.327, 0.327, 0.354, 0.319, 0.344, 0.362, 0.391, 0.306, 0.236, 0.218, 0.168,
                               0.154, 0.162), 
                       ll15 = c(0.115, 0.115, 0.140, 0.114, 0.148, 0.174, 0.200, 0.148, 0.113, 0.098, 0.074, 0.065, 0.072)) %>%
  mutate(init_25 = dul - (0.75*(dul-ll15)),
         init_50 = dul - (0.5*(dul-ll15)),
         init_75 = dul - (0.25*(dul-ll15)))

sw_df_lima <- data.frame(dul = c(0.280, 0.280, 0.279, 0.290, 0.252),
                         ll15 = 0.120, 0.120, 0.132, 0.157, 0.110) %>%
   mutate(init_25 = dul - (0.75*(dul-ll15)),
         init_50 = dul - (0.5*(dul-ll15)),
         init_75 = dul - (0.25*(dul-ll15)))
                       


adj_gaps_yields_mc %>%
  ggplot(aes(x = year_plant, y = yield_gap, colour = soil_scenario)) +
  geom_point(size = 2.5) +
  scale_color_manual(values = c("blue","darkgreen", "red")) + 
  facet_grid(cols = vars(plant_scenario), rows = vars(State), scales = "free_x") +
  theme_pubr() +
  labs(y = "Simulated soybean yield gap (NT:Till)", x = "Year", color = "")




### Plot to look at water def and yield gap
yg_water_def_plot <- adj_gaps_yields %>%
  ggplot(aes(x = frac_water, y = yield_kg_ha)) +
  geom_point(size = 3, aes(colour = State, shape = plant_scenario, alpha = soil_scenario)) +
  geom_abline(slope = 1, intercept = 0) +
  theme_pubr() +
  facet_grid(cols = vars(soil_scenario)) +
  geom_smooth(method = "lm", se = F, formula = y ~ poly(x, 2)) +
  scale_color_manual(values = c("red", "black")) +
  labs(x = "FASW NT - FASW Till", y = "Simulated soybean yield gap (NT:Till)", color = "", shape = "") +
  theme(legend.text = element_text(size = 16),
        axis.title = element_text(size = 16),
        axis.text = element_text(size = 16)) +
  #annotate(geom = "text",label = paste0("RMSE = ", round(rmse_gap,2)), x = 0.6, y = 0.99, size = 5) +
  #annotate(geom = "text",label = paste0("RRMSE = ", round(rrmse_gap*100,2),"%"), x = 0.6, y = 0.965, size = 5) +
  stat_poly_eq(use_label("eq", "R2"),formula = y ~ poly(x,2)) 

ggsave(yg_sim_obs_plot, filename = "Figures/yg_sim_obs_plot.png",
       dpi = 300, width = 9, height = 6, units = "in")


### Table for PAW for all soils

paw_table <- expand_grid(soil_series = c("Plano", "Lima"),
                        soil_scenario = c("Low", "Med", "High")) %>%
  mutate(pawc_mm = case_when(
    soil_series == "Plano" & soil_scenario == "Low" ~ 183.4,
    soil_series == "Plano" & soil_scenario == "Med" ~ 383.6,
    soil_series == "Plano" & soil_scenario == "High" ~ 567.1,
    soil_series == "Lima" & soil_scenario == "Low" ~ 77.4,
    soil_series == "Lima" & soil_scenario == "Med" ~ 125.4,
    soil_series == "Lima" & soil_scenario == "High" ~ 171.2,
  ), State = case_when(
    soil_series == "Plano" ~ "WI",
    soil_series == "Lima" ~ "NY"
  ))

adj_gaps_pawc <- adj_gaps_yields %>%
  left_join(paw_table, by = c("State", "soil_scenario")) %>%
  group_by(State, year_plant, soil_scenario, plant_scenario) %>%
  mutate(pawc_frac = pawc_mm*frac_water,
         pawc_diff = pawc_frac[Tillage == "Till"]-pawc_frac[Tillage == "NT"],
         pawc_frac_diff = pawc_diff/pawc_mm)


adj_gaps_pawc %>%
  ggplot(aes(x = -pawc_frac_diff, y = yield_gap)) +
  geom_point(size = 3, aes(colour = State)) +
 # geom_abline(slope = 1, intercept = 0) +
  theme_pubr() +
  facet_grid(rows = vars(plant_scenario),cols = vars(soil_scenario)) +
  scale_color_manual(values = c("red", "black")) +
  labs(x = "Till - NT PAW", y = "Simulated soybean yield gap (NT:Till)", color = "", shape = "") +
  stat_poly_line(se = F) +
  theme(legend.text = element_text(size = 16),
        axis.title = element_text(size = 16),
        axis.text = element_text(size = 16)) +
  #annotate(geom = "text",label = paste0("RMSE = ", round(rmse_gap,2)), x = 0.6, y = 0.99, size = 5) +
  #annotate(geom = "text",label = paste0("RRMSE = ", round(rrmse_gap*100,2),"%"), x = 0.6, y = 0.965, size = 5) +
  stat_poly_eq(use_label("eq", "R2")) 


#### The same as above, but for soils with discrete MC draws


apsim_yg_def_mc <- read_xlsx("soygap_analysis_proj.xlsx")

apsim_defs_adj_mc <- apsim_yg_def_mc %>%
  mutate(date = as.Date(Clock.Today)) %>%
  dplyr::select(Zone, date,frac_water) %>%
  separate_wider_delim(cols = Zone, delim = " ", names = c("State", "Tillage", "year_plant", "soil_scenario", "plant_scenario")) %>%
  mutate(site_year = paste0(State,"-",year_plant))

df_filtered_mc <- apsim_defs_adj_mc %>%
  semi_join(pd_filtered, by = c("date" = "SoySeedingDate","site_year")) %>%
  dplyr::select(State, Tillage, year_plant, soil_scenario, plant_scenario, frac_water)


apsim_yg_yields_adj_mc <- apsim_yg_def_mc %>%
  group_by(Zone) %>%
  summarise(yield_kg_ha = max(soy_kg_ha),
            rye_bm_kg_ha = max(rye_bm_kg_ha)) %>%
  #filter(Zone != "Fallow Field", Zone != "Rye Field") %>%
  separate_wider_delim(cols = Zone, delim = " ", names = c("State", "Tillage", "year_plant", "soil_scenario", "plant_scenario")) %>%
  mutate(soil_scenario = factor(soil_scenario, levels = c("Low", "Med", "High"))) %>%
  left_join(df_filtered)

rye_ylds <- apsim_yg_yields_adj_mc %>%
  filter(rye_bm_kg_ha > 0,
         Tillage == "NT") %>%
  dplyr::select(-yield_kg_ha) %>%
  mutate(site_year = paste0(State, year_plant),
         type = rep("sim"))  %>%
  dplyr::select(site_year, State, rye_bm_kg_ha)
  
rye_obs_adj <- rye_obs %>%
  ungroup() %>%
  mutate(site_year = paste0(State, Year), 
         rye_bm_kg_ha = final_rye) %>%
  filter(site_year %in% rye_ylds$site_year) %>%
  dplyr::select(site_year, State, rye_bm_kg_ha)


apsim_gaps_adj_mc <- apsim_yg_yields_adj_mc %>%
  group_by(State, year_plant, soil_scenario, plant_scenario) %>%
  mutate(yield_gap = yield_kg_ha[Tillage == "NT"]/yield_kg_ha[Tillage == "Till"],
         water_frac_dif = frac_water[Tillage == "Till"]-frac_water[Tillage == "NT"])



  

adj_gaps_joined_mc <- left_join(apsim_gaps_adj_mc, obs_yg_adj) %>%
  mutate(Year = as.numeric(year_plant),
         site_year = paste0(State, "-",Year))

obs_rain <- metagen_result_final %>%
  filter(site_year %in% adj_gaps_joined_mc$site_year)

gaps_prcp <- adj_gaps_joined_mc %>%
  left_join(obs_rain, by ="site_year") 


gaps_prcp %>%
  ggplot(aes(x = plant_prcp, y = yield_gap.x)) +
  geom_point(aes(colour = State.x)) +
  facet_grid(cols = vars(soil_scenario), rows = vars(plant_scenario)) +
  stat_poly_eq()

mod_ef <- function(pred, obs){
  mse = sum((pred-obs)^2)
  mse_obs = sum((obs-mean(obs))^2)
  ef = 1-(mse/mse_obs)
}

adj_gaps_yields_mc <- left_join(adj_gaps_joined_mc, proj_yields, by = c("State", "Tillage" = "Till_NT", "Year")) %>%
  mutate(obs_yld = mean_yld) %>%
  ungroup() %>%
  group_by(soil_scenario, plant_scenario) %>%
  mutate(rmse_gap = Metrics::rmse(yield_ratio, yield_gap),
         rrmse_gap = rmse_gap/mean(yield_ratio),
         rmse_yield = rmse(mean_yld, yield_kg_ha),
         rrmse_yield = rmse_yield/mean(mean_yld),
         ef_gap = mod_ef(pred = yield_gap, obs = yield_ratio),
         ef_yield = mod_ef(pred = yield_kg_ha, obs = mean_yld),
         soil_scenario = factor(soil_scenario, levels = c("High", "Med", "Low")),
         plant_scenario = factor(plant_scenario, levels = c("PD", "SR")))

# Graph comparing yields

adj_soy_yield_mc_plot <- adj_gaps_yields_mc %>%
  ggplot(aes(x = mean_yld, y = yield_kg_ha)) +
  geom_point(size = 2, aes(colour = State)) +
  geom_abline(slope = 1, intercept = 0) +
  theme_pubr() +
  facet_grid(rows = vars(soil_scenario),cols = vars(plant_scenario)) +
  scale_color_manual(values = c("red", "black")) +
  coord_cartesian(ylim = c(1000, 5000), xlim = c(1000,5000)) +
  geom_text(aes(label = paste0("RMSE = ", round(rmse_yield,2)), x = 1320, y = 4300), size = 4,inherit.aes = F) +
  geom_text(aes(label = paste0("RRMSE = ", round(rrmse_yield*100,2),"%"), x = 1320, y = 3800), size = 4,inherit.aes = F) +
  geom_text(aes(label = paste0("EF = ", round(ef_yield,2)), x = 1320, y = 3300), size = 4, inherit.aes = F) +
  labs(x = "Observed soybean yield (kg/ha)", y = "Simulated soybean yield (kg/ha)", color = "", shape = "") +
  geom_smooth(method = "lm", se = F, color = "gray", linetype = "dashed") +
  stat_poly_eq(size = 4) +
  theme(legend.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 14))

ggsave(adj_soy_yield_mc_plot, filename = "Figures/yield_sim_obs_plot_mc.png",
       dpi = 300, width = 12, height = 8, units = "in")

gap_ratio_mc_plot <- adj_gaps_yields_mc %>%
  ggplot(aes(x = yield_ratio, y = yield_gap)) +
  geom_point(size = 3, aes(colour = State)) +
  geom_abline(slope = 1, intercept = 0) +
  theme_pubr() +
  facet_grid(rows = vars(soil_scenario) , cols = vars(plant_scenario)) +
  scale_color_manual(values = c("red", "black")) +
  coord_cartesian(ylim = c(0.5, 1.2), xlim = c(0.5,1.2)) +
  labs(x = "Observed soybean yield gap", y = "Simulated soybean yield gap", color = "", shape = "") +
  theme(legend.text = element_text(size = 16),
        axis.title = element_text(size = 16),
        axis.text = element_text(size = 16)) +
  geom_text(aes(label = paste0("RMSE = ", round(rmse_gap,2)), x = 0.56, y = 1.1), size = 4,inherit.aes = F) +
  geom_text(aes(label = paste0("RRMSE = ", round(rrmse_gap*100,2),"%"), x = 0.56, y = 1.04), size = 4,inherit.aes = F) +
  geom_text(aes(label = paste0("EF = ", round(ef_gap,2)), x = 0.56, y = 0.98), size = 4, inherit.aes = F) +
  stat_poly_eq(size = 4) 

ggsave(gap_ratio_mc_plot, filename = "Figures/gap_sim_obs_plot_mc.png",
       dpi = 300, width = 12, height = 8, units = "in")

### Plot to look at water def and yield gap
fasw_plot_ex <- adj_gaps_joined_mc %>%
  ggplot(aes(x = water_frac_dif, y = yield_gap)) +
  geom_point(size = 3, aes(colour = State, shape = plant_scenario)) +
  geom_abline(slope = 1, intercept = 0) +
  theme_pubr() +
  facet_grid(cols = vars(soil_scenario), rows = vars(plant_scenario)) +
  geom_smooth(method = "lm", se = F) +
  scale_color_manual(values = c("red", "black")) +
  labs(x = "FASW NT - FASW Till", y = "Simulated soybean yield gap (NT:Till)", color = "", shape = "") +
  theme(legend.text = element_text(size = 16),
        axis.title = element_text(size = 16),
        axis.text = element_text(size = 16)) +
  stat_poly_eq(use_label("eq", "R2"), label.x = "right") 



adj_gaps_pawc_mc <- adj_gaps_joined_mc %>%
  left_join(paw_table, by = c("State", "soil_scenario")) %>%
  group_by(State, year_plant, soil_scenario, plant_scenario) %>%
  mutate(pawc_frac = pawc_mm*frac_water,
         pawc_diff = pawc_frac[Tillage == "Till"]-pawc_frac[Tillage == "NT"],
         pawc_frac_diff = pawc_diff/pawc_mm)


till_nt_water <- adj_gaps_pawc_mc %>% 
  ggplot(aes(x = pawc_diff, y = yield_gap)) +
  geom_point(size = 3, aes(colour = State)) +
 # geom_abline(slope = 1, intercept = 0) +
  theme_bw() +
  facet_grid(rows = vars(plant_scenario),cols = vars(soil_scenario), scales = "free_x") +
  scale_color_manual(values = c("red", "black")) +
  labs(x = "Till - NT PAW", y = "Simulated soybean yield gap (NT:Till)", color = "", shape = "") +
  stat_poly_line(se = F) +
  theme(legend.text = element_text(size = 16),
        axis.title = element_text(size = 16),
        axis.text = element_text(size = 16),
        legend.position = "top") +
  #annotate(geom = "text",label = paste0("RMSE = ", round(rmse_gap,2)), x = 0.6, y = 0.99, size = 5) +
  #annotate(geom = "text",label = paste0("RRMSE = ", round(rrmse_gap*100,2),"%"), x = 0.6, y = 0.965, size = 5) +
  stat_poly_eq(use_label("eq", "R2"), label.x = "right", label.y = "top") 
ggsave(till_nt_water, filename = "Figures/tnt_water_graph_example.png", dpi = 300,
       width = 9, height = 6, units = "in")

##theme_linedraw()#### Checking phenology comparison of APSIM to Liebert data
obs_rye_phen <- read_xlsx("~/Downloads/rye_exp_197.xlsx", sheet = "Sheet1") %>%
  dplyr::select(Clock.Today, zadoks) %>%
  rename("zadok_obs" = zadoks) 


phen_rye <- read_xlsx("~/Downloads/rye_exp_197.xlsx", sheet = "Report") %>%
  dplyr::select(Clock.Today, zadok) %>% 
  filter(Clock.Today %in% obs_rye_phen$Clock.Today) %>%
  rename("zadok_sim" = zadok)

obs_sim_rye_phen <- left_join(obs_rye_phen, phen_rye)

rrmse_rye_phen <- round((Metrics::rmse(obs_sim_rye_phen$zadok_obs, obs_sim_rye_phen$zadok_sim)/mean(obs_sim_rye_phen$zadok_obs))*100,2)
pred_obs_rye_phen <- obs_sim_rye_phen %>%
  ggplot(aes(x = zadok_obs, y = zadok_sim)) +
  geom_point(size = 2.5) +
  geom_abline() +
  theme_pubr() +
  stat_poly_eq(size = 5) +
  annotate("text", x = 35, y = 69, label = paste0("RRMSE =",rrmse_rye_phen,"%"), size = 5) +
  labs(x = "Observed zadoks stage", y = "Simulated zadoks stage") +
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 14))

ggsave(pred_obs_rye_phen, filename = "Figures/cr_pred_obs_phenology.png",
       dpi = 300, width = 9, height = 6, units = "in")
#### Liner mixed models with APSIM data

def_mod_apsim <- lmer(yield_gap ~ water_frac_dif * as.factor(soil_scenario) * as.factor(plant_scenario) + (1|State), data = adj_gaps_yields)

emm_def_apsim <- emmeans(def_mod_apsim, ~as.factor(soil_scenario)*as.factor(plant_scenario), adjust = "sidak")
pairs(emm_def_apsim)
emm_trends_apsim <- emtrends(def_mod_apsim, ~ as.factor(soil_scenario) * as.factor(plant_scenario), var = "water_frac_dif")
plot(emm_trends_apsim)

pairs(emm_trends_apsim)
pairs(emm_trends_apsim)



```

```{r APSIM Factorial Experiment}

apsim_factorial <- read_xlsx("factorial_scenario_analysis.xlsx", sheet = "Report")


apsim_factorial <- apsim_factorial %>%
  mutate(swat_scenario = word(Zone, -1),
         state = case_when(
           startsWith(Zone, "Wisconsin") ~ "Wisconsin",
           startsWith(Zone, "New York") ~ "New York"
         ),
         swat_scenario = case_when(
           swat_scenario == "25" ~ "25%",
           swat_scenario == "50" ~ "50%",
           swat_scenario == "75" ~ "75%",
           swat_scenario == "Full" ~ "100%"
         ),
         swat_scenario = factor(swat_scenario, levels = c("100%", "75%", "50%", "25%")),
         plant_population = 10000*as.numeric(Pop))

apsim_factorial %>%
  #separate_wider_delim()
  #group_by(Experiment, Pop, Zone,Clock.Today.Year) %>%
  #dplyr::summarise(mean_soy = mean(soy_kg_ha)) %>%
  filter(state == "New York") %>%
  ggplot(aes(x = factor(Clock.Today.Year), y = soy_kg_ha, fill = swat_scenario)) +
  geom_boxplot(position = position_dodge()) +
  scale_fill_brewer(palette = "Set3") +
  facet_wrap(~plant_population) +
  theme_pubr() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5),
        legend.position = "top") +
  labs(y = "Soybean yield (kg/ha)", x = "Year", fill = "")

ap_fac_mod <- lmer(soy_kg_ha ~ (Pop*swat_scenario*Date*state) + (1|state), data = apsim_factorial)
summary(ap_fac_mod)
check_model(ap_fac_mod)

emm_fac_apsim <- emmeans(ap_fac_mod, ~(swat_scenario*Pop)|state)

multcomp::cld(emm_fac_apsim,
              Letters = "abcdefghijklmn", 
              reversed = T)

pairs(emm_fac_apsim)

contrast(emm_fac_apsim,
         method = "trt.vs.ctrl",
         ref = "100% Pop61.8")


emm_fac_pop_by_swat <- emmeans(ap_fac_mod, ~(Pop|swat_scenario)|state)
emm_pop_by_swat_pair <- pairs(emm_fac_pop_by_swat)
#### Factorial experiment based on rye vwc results 

apsim_factorial_rye_water <- read_xlsx("~/Downloads/factorial_with_rye_water.xlsx", sheet = "Report")


apsim_factorial_rye_water <- apsim_factorial_rye_water %>%
  mutate(swat_scenario = word(Zone, -1),
         state = case_when(
           startsWith(Zone, "Wisconsin") ~ "Wisconsin",
           startsWith(Zone, "New York") ~ "New York"
         ),
         swat_scenario = case_when(
           swat_scenario == "95" ~ "97.5%",
           swat_scenario == "75" ~ "75%",
           swat_scenario == "50" ~ "50%",
           swat_scenario == "25" ~ "25%",
           swat_scenario == "5" ~ "2.5%"
         ),
         swat_scenario = factor(swat_scenario, levels = c("97.5%", "75%", "50%", "25%", "2.5%")),
         plant_population = 10000*as.numeric(Pop),
         rye_bin = case_when(
           between(as.numeric(Bm), 1000, 4000) ~ "Low cereal rye",
           between(as.numeric(Bm), 5000, 8000) ~ "Middle cereal rye",
           between(as.numeric(Bm), 9000, 12000) ~ "High cereal rye",
         ),
         tillage = case_when(
           endsWith(Experiment, "Till") ~ "Till",
           endsWith(Experiment, "NT") ~ "NT"
         )) %>%
  filter(tillage == "NT")

lm_pop_wat_simp <- lmer(soy_kg_ha ~ (Pop+swat_scenario)*state + (1|state), data = apsim_factorial_rye_water)

pop_wat_letters <-emmeans(lm_pop_wat_simp, ~ ~(Pop+swat_scenario)|state, type = "response") %>% 
  cld(Letters = "abcdefghijklmnop", reversed = TRUE, adjust = "bonferroni") %>% 
  as_tibble() %>% 
  mutate(.group = trimws(.group))

MeanPlusSe <- function(x) mean(x, na.rm = TRUE) + plotrix::std.error(x, na.rm = TRUE)

ny_fac_ex_plot <- left_join(pop_wat_letters, apsim_factorial_rye_water) %>%
  ggplot(aes(x = Pop, y = soy_kg_ha, fill = swat_scenario)) +
  stat_summary(geom = "col", fun = "mean" ,position = position_dodge(), color = "black") +
  stat_summary(geom = "errorbar", fun.data = "mean_se" ,position = position_dodge(width = 0.9), width = 0.3) +
  stat_summary(geom = "text", fun = "MeanPlusSe", aes(label =.group), vjust = -0.8, size = 4, position = position_dodge(width = 0.9)) +
  scale_fill_brewer(palette = "Set3") + 
  facet_grid(cols = vars(state)) +
  theme_pubr() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5),
        legend.position = "top") +
  labs(y = "Soybean yield (kg/ha)", x = "Plant population (plants/ha)", fill = "")
ggsave(ny_fac_ex_plot, filename = "Figures/ny_fac_ppop_swat.png", dpi = 300,
       height = 6, width = 12, units = "in")
##### Chat recommendation
# 1) prepare data: treat Pop as categorical for plotting/comparisons
df <- apsim_factorial_rye_water %>%
  mutate(
    Pop = factor(Pop),
    swat_scenario = factor(swat_scenario),
    state = factor(state),
    site_year = paste0(state, Clock.Today.Year)
  )

# 2) fit model
# OPTION A (recommended for within-state contrasts): treat state as a fixed effect
lm_pop_wat_simp <- lmer(soy_kg_ha ~ Pop * swat_scenario * state + (1|state:site_year), data = df)

# (If you truly need state as a random effect instead, use: 
# lm_pop_wat_simp <- lmer(soy_kg_ha ~ Pop * swat_scenario + (1|state), data = df)
# but then interpret CLDs carefully — see notes below.)

# 3) emmeans for Pop x swat_scenario *within each state*
emm <- emmeans(lm_pop_wat_simp, ~ Pop * swat_scenario | state, type = "response")

# compute CLD letters (no ~ funny business)
pop_wat_letters <- cld(emm,
                       Letters = "abcdefghijklmnop",
                       adjust = "bonferroni",
                       reversed = TRUE) %>%
  as_tibble() %>%
  mutate(.group = trimws(.group))


# 4) compute a summary dataframe (means, SE, 95% CI) from the raw data
summary_df <- df %>%
  group_by(state, Pop, swat_scenario) %>%
  summarise(
    mean = mean(soy_kg_ha, na.rm = TRUE),
    sd = sd(soy_kg_ha, na.rm = TRUE),
    n = sum(!is.na(soy_kg_ha)),
    se = sd / sqrt(n),
    df = n - 1,
    lower = mean - qt(0.975, df) * se,
    upper = mean + qt(0.975, df) * se,
    .groups = "drop"
  )

# 5) join letters (one row per group)
plot_df <- left_join(summary_df, pop_wat_letters,
                     by = c("state", "Pop", "swat_scenario"))

# small vertical offset for letters (2% of y-range)
yrange <- max(plot_df$upper, na.rm = TRUE) - min(plot_df$lower, na.rm = TRUE)
plot_df <- plot_df %>% mutate(letter_y = upper + 0.02 * yrange)

# 6) plot with consistent dodging
ny_fac_ex_plot <- ggplot(plot_df, aes(x = Pop, y = mean, fill = swat_scenario)) +
  geom_col(position = position_dodge(width = 0.9), color = "black") +
  geom_errorbar(aes(ymin = lower, ymax = upper),
                position = position_dodge(width = 0.9),
                width = 0.25) +
  geom_text(aes(label = .group, y = letter_y),
            position = position_dodge(width = 0.9),
            vjust = 0,
            size = 4) +
  facet_grid(cols = vars(state)) +
  scale_fill_brewer(palette = "Set3") +
  theme_pubr() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5),
        legend.position = "top") +
  labs(y = "Soybean yield (kg/ha)", x = "Plant population (plants/ha)", fill = "")

ny_fac_ex_plot


#####


wi_fac_ex_plot <- apsim_factorial_rye_water %>%
  filter(state == "Wisconsin",
         tillage == "NT") %>%
  ggplot(aes(x = factor(Clock.Today.Year), y = soy_kg_ha, fill = factor(plant_population))) +
  geom_boxplot(position = position_dodge()) +
  scale_fill_brewer(palette = "Set3") +
  facet_grid(cols = vars(swat_scenario)) +
  theme_pubr() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5),
        legend.position = "top") +
  labs(y = "Soybean yield (kg/ha)", x = "Year", fill = "")
ggsave(wi_fac_ex_plot, filename = "Figures/wi_fac_ppop_swat.png", dpi = 300,
       height = 6, width = 12, units = "in")


ap_rye_wat_mod <- lmer(soy_kg_ha ~ (rye_bin*swat_scenario*Pop*state) + (1|state), data = apsim_factorial_rye_water)
summary(ap_rye_wat_mod)
check_model(ap_rye_wat_mod)

#### Looking at some random forest

library(caret)
library(randomForest)
ap_fac_rye_water_rf_ny <- apsim_factorial_rye_water %>%
  filter(tillage == "NT",
         state == "New York") %>%
  mutate(Date = factor(Date, levels = c("20-may", "25-may", "30-may", "4-jun",  "9-jun", "14-jun")),
         Pop = factor(Pop),
         Bm = factor(Bm, levels = c("1000", "3000", "5000","7000", "9000", "11000")),
         swat_scenario = factor(swat_scenario))
  

set.seed(123)
train_index <- createDataPartition(ap_fac_rye_water_rf_ny$soy_kg_ha, p = 0.7, list = FALSE)
train_data <- ap_fac_rye_water_rf_ny[train_index, ]
test_data  <- ap_fac_rye_water_rf_ny[-train_index, ]

# Define training control (cross-validation)
ctrl <- trainControl(method = "cv",  # k-fold cross-validation
                     number = 5,     # number of folds
                     verboseIter = TRUE)

# Train random forest model
set.seed(123)
rf_model <- randomForest(soy_kg_ha ~ Pop + Date + Bm + swat_scenario, 
                  data = train_data,
                  method = "rf",
                  trControl = ctrl,
                  tuneLength = 5,   # number of mtry values to try
                  importance = TRUE)

# View model results
print(rf_model)
plot(rf_model)

# Variable importance
varImpPlot(rf_model)

importance(rf_model)

# Predict on test set
predictions <- predict(rf_model, newdata = test_data)


###

emm_rye_wat_swat_by_pop <- emmeans(ap_rye_wat_mod, ~(swat_scenario+Pop+rye_bin)|state)

emm_rye_wat_swat_by_pop@levels

contrast(emm_rye_wat_swat_by_pop,
         method = "trt.vs.ctrl",
         ref = "50% Pop61.8 Middle cereal rye")

emm_swat_by_pop_pair <- pairs(emm_rye_wat_swat_by_pop)
emm_rye_wat_pop_by_swat <- emmeans(ap_rye_wat_mod, ~(Pop|swat_scenario)|state)
emm_pop_by_swat_pair <- pairs(emm_rye_wat_pop_by_swat)


multcomp::cld(emm_rye_wat_swat_by_pop,
              Letters = "abcdefghijklmn", 
              reversed = T)
#### Checking out variation in soil water withdrawl of cereal rye across management scenarios
vwc_ny <- clean_names(read_xlsx("~/Downloads/rye_exp_197.xlsx", sheet = "Report")) %>%
  pivot_longer(cols = soil_vwc_1:soil_vwc_7, values_to = "vwc_val", names_to = "vwc_wat") %>%
  mutate(layer = case_when(endsWith(vwc_wat, "_1") ~ "1",
    endsWith(vwc_wat, "_2") ~ "2",
    endsWith(vwc_wat, "_3") ~ "3",
    endsWith(vwc_wat, "_4") ~ "4",
    endsWith(vwc_wat, "5") ~ "5",
    endsWith(vwc_wat, "6") ~ "6",
    endsWith(vwc_wat, "7") ~"7")) %>%
  group_by(simulation_name, clock_today_year) %>%
  mutate(paw_prox = sum(vwc_val))


ny_vwc_quantiles <- vwc_ny %>%
  group_by(layer) %>%
  summarise(vwc_5 = quantile(vwc_val, probs = 0.025),
            vwc_25 = quantile(vwc_val, probs = 0.25),
            vwc_50 = quantile(vwc_val, probs = 0.5),
            vwc_75 = quantile(vwc_val, probs = 0.75),
            vwc_95 = quantile(vwc_val, probs = 0.975))

ecdf_rye <- ecdf(vwc_ny$rye_kg_ha)

ecdf_rye(6000)

vwc_ny %>%
  ggplot(aes(x = vwc_val)) +
  geom_histogram() +
  facet_wrap(~layer)

vwc_ny

ny_rye_quantiles <- vwc_ny %>%
  summarise(vwc_5 = quantile(rye_kg_ha, probs = 0.025),
            vwc_50 = quantile(rye_kg_ha, probs = 0.50),
            vwc_95 = quantile(rye_kg_ha, probs = 0.975))

ny_rye_cn <- vwc_ny %>%
  summarise(vwc_5 = quantile(c_to_n, probs = 0.025),
            vwc_50 = quantile(c_to_n, probs = 0.5),
            vwc_95 = quantile(c_to_n, probs = 0.975))


vwc_wi <-clean_names(read_xlsx("~/Downloads/rye_exp_197.xlsx", sheet = "ReportWI")) %>%
  pivot_longer(cols = soil_vwc_1:soil_vwc_13, values_to = "vwc_val", names_to = "vwc_wat") %>%
  mutate(layer = case_when(
    endsWith(vwc_wat, "_1") ~ "1",
    endsWith(vwc_wat, "_2") ~ "2",
    endsWith(vwc_wat, "_3") ~ "3",
    endsWith(vwc_wat, "_4") ~ "4",
    endsWith(vwc_wat, "5") ~ "5",
    endsWith(vwc_wat, "6") ~ "6",
    endsWith(vwc_wat, "7") ~"7",
    endsWith(vwc_wat, "8") ~ "8",
    endsWith(vwc_wat, "9") ~ "9",
    endsWith(vwc_wat, "_10") ~ "10",
    endsWith(vwc_wat, "_11") ~ "11",
    endsWith(vwc_wat, "_12") ~ "12",
    endsWith(vwc_wat, "_13") ~ "13"
  ),
  layer = factor(layer,levels = c("1","2","3","4","5","6","7","8","9","10","11","12","13")))



range(vwc_ny$soil_vwc_6)
  
vwc_ny %>%
  ggplot(aes(x = factor(fasw_wat), y = fasw_val)) +
  geom_boxplot(position = position_dodge()) +
  geom_boxplot(position = position_dodge()) +
  scale_fill_brewer(palette = "Set3") +
  theme_pubr() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5),
        legend.position = "top") +
  labs(y = "Percent water capacity", x = "Layer of soil", fill = "")

vwc_wi %>%
  ggplot(aes(x = layer, y = vwc_val)) +
  geom_boxplot(position = position_dodge()) +
  geom_boxplot(position = position_dodge()) +
  scale_fill_brewer(palette = "Set3") +
  theme_pubr() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5),
        legend.position = "top") +
  labs(y = "Percent water capacity", x = "Layer of soil", fill = "")

wi_vwc_quantiles <- vwc_wi %>%
  group_by(layer) %>%
  summarise(vwc_5 = quantile(vwc_val, probs = 0.025),
            vwc_25 = quantile(vwc_val, probs = 0.25),
            vwc_50 = quantile(vwc_val, probs = 0.5),
            vwc_75 = quantile(vwc_val, probs = 0.75),
            vwc_95 = quantile(vwc_val, probs = 0.975))

wi_rye_quantiles <- vwc_wi %>%
  summarise(rye_5= quantile(rye_kg_ha, probs = 0.025),
            rye_50 = quantile(rye_kg_ha, probs = 0.5),
            rye_95 = quantile(rye_kg_ha, probs = 0.975))

wi_rye_cn <- vwc_wi %>%
  summarise(rye_5= quantile(c_to_n, probs = 0.025),
            rye_50 = quantile(c_to_n, probs = 0.5),
            rye_95 = quantile(c_to_n, probs = 0.975))

#### Same as above but for tilled scenarios

vwc_ny_till <- clean_names(read_xlsx("~/Downloads/till_soy_swat.xlsx", sheet = "Report")) %>%
  pivot_longer(cols = soil_vwc_1:soil_vwc_7, values_to = "vwc_val", names_to = "vwc_wat") %>%
  mutate(layer = case_when(endsWith(vwc_wat, "_1") ~ "1",
    endsWith(vwc_wat, "_2") ~ "2",
    endsWith(vwc_wat, "_3") ~ "3",
    endsWith(vwc_wat, "_4") ~ "4",
    endsWith(vwc_wat, "5") ~ "5",
    endsWith(vwc_wat, "6") ~ "6",
    endsWith(vwc_wat, "7") ~"7"))




ny_vwc_quantiles_till <- vwc_ny_till %>%
  group_by(layer) %>%
  summarise(vwc_5 = quantile(vwc_val, probs = 0.025),
            vwc_25 = quantile(vwc_val, probs = 0.25),
            vwc_50 = quantile(vwc_val, probs = 0.5),
            vwc_75 = quantile(vwc_val, probs = 0.75),
            vwc_95 = quantile(vwc_val, probs = 0.975))


vwc_wi_till <-clean_names(read_xlsx("~/Downloads/till_soy_swat.xlsx", sheet = "ReportWI")) %>%
  pivot_longer(cols = soil_vwc_1:soil_vwc_13, values_to = "vwc_val", names_to = "vwc_wat") %>%
  mutate(layer = case_when(
    endsWith(vwc_wat, "_1") ~ "1",
    endsWith(vwc_wat, "_2") ~ "2",
    endsWith(vwc_wat, "_3") ~ "3",
    endsWith(vwc_wat, "_4") ~ "4",
    endsWith(vwc_wat, "5") ~ "5",
    endsWith(vwc_wat, "6") ~ "6",
    endsWith(vwc_wat, "7") ~"7",
    endsWith(vwc_wat, "8") ~ "8",
    endsWith(vwc_wat, "9") ~ "9",
    endsWith(vwc_wat, "_10") ~ "10",
    endsWith(vwc_wat, "_11") ~ "11",
    endsWith(vwc_wat, "_12") ~ "12",
    endsWith(vwc_wat, "_13") ~ "13"
  ),
  layer = factor(layer,levels = c("1","2","3","4","5","6","7","8","9","10","11","12","13")))




wi_vwc_quantiles_till <- vwc_wi_till %>%
  group_by(layer) %>%
  summarise(vwc_5 = quantile(vwc_val, probs = 0.025),
            vwc_25 = quantile(vwc_val, probs = 0.25),
            vwc_50 = quantile(vwc_val, probs = 0.5),
            vwc_75 = quantile(vwc_val, probs = 0.75),
            vwc_95 = quantile(vwc_val, probs = 0.975))


```

